### ISSUE TITLE
[두께] 두께 변경아이콘을 여러번 선택해야 두께 변경 가능한 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#100]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/4cyRdwSv3Vc
- 항목 및 설명 : 형광펜 선택 후 두께 변경 아이콘 선택 시 한번에 출력되지 않고, 여러번 선택해야되는 문제입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by KiyeonSeo** [comment]
@minihallo 프로님, 지우개 선택하고 두께 선택 시 두께 선택창이 나오지 않는 경우가 간혹 발견됩니다.
