### ISSUE TITLE
[불러오기] 데이터 불러오기 시(.GRIDA) 필기 데이터 불러오지 못하고 빈 페이지로만 표시되는 이슈

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#101]
- 버전: 그리다 보드 2.0
- 접속경로 : https://gridaboard-v2-test.web.app/

데이터 불러오기 시(.GRIDA) 필기 데이터 불러오지 못하고 빈 페이지로만 표시되는 이슈입니다.

**Comment by KiyeonSeo** [comment]
@yeji-qa 책임님, 처리 되었습니다. 확인 요청 드립니다.
