### ISSUE TITLE
[형광펜] 형광펜 선택 후 펜으로 필기 시 페이지 뷰에 필기가 끊겨서 표시되는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#102]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/h623yYD8ONY
- 항목 및 설명 : 형광펜 선택 후 두께 변경하면서 펜으로 필기 시 화면에 매끄럽게 표시되지 않는 문제입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by minihallo-neo** [comment]
펜 두께가 일정값 이상으로 커졌을 때 렌더링 과정에서 발생하는 오류입니다. 우선 최대 두께를 줄여서 해결했습니다.

**Comment by KiyeonSeo** [comment]
@songkyungha 책임님, 처리되었습니다. 확인 요청 드립니다.
