### ISSUE TITLE
[이미지 저장] PDF 파일로 이미지 저장 시 지우개로 지운 데이터까지 모두 추출되는 이슈

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#103]
-버전: 그리다 보드 2.0
-접속경로 : https://gridaboard-v2-test.web.app/

PDF 파일로 이미지 저장 시 지우개로 지운 데이터까지 모두 추출되는 이슈 입니다.

[재현경로]
1. 그리다 보드 2.0 접속
2. 펜 연결 후 임의 필기
3. 지우개 아이콘으로 필기 삭제
4. PDF 파일로 이미지 저장

**Comment by minihallo-neo** [comment]
지우개 스트로크가 저장되어 발생한 문제고 지우개 스트로크는 저장되지 않도록 수정해서 해결했습니다

**Comment by KiyeonSeo** [comment]
@yeji-qa 책임님, 처리되었습니다. 확인 요청 드립니다.
