### ISSUE TITLE
[두께] F30(dimo) 연결하여 두께 변경하면서 필기 시 두께 출력 오류

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#105]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/0roPKViTYjM
- 항목 및 설명 : F30(dimo)펜 연결하여 두께 변경 후 필기 시도 시 두께가 변경 된건지 크게 차이 나지 않고, 두께 1단계 선택 시 화면에 거의 표시되지 않을 정도의 두께로 출력됩니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by minihallo-neo** [comment]
펜 별로 필압이 다르게 들어와 발생한 문제며 펜 모델별로 필압 보정해서 해결했습니다.
