### ISSUE TITLE
[펜 연결] 펜 연결된 상태에서 펜 전원 OFF 시 펜 아이콘은 연결된것 처럼 보이는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#106]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/iE5ivi6mkb0
- 항목 및 설명 : 펜 연결된 상태에서 펜 전원 OFF 시도 > 연결된 펜 아이콘 확인 시 연결 유지된것 처럼 보이는 문제입니다. 
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by KiyeonSeo** [comment]
@songkyungha 책임님, 처리 되었습니다. 확인 요청 드립니다.
