### ISSUE TITLE
[인쇄 페이지 순서 등록] 인쇄 페이지 순서 등록 화면에서 펜 연결 시 아이콘이 연결안된 상태로 보이는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#107]
- 발견 일시 : 2021.03.24
- 화면 : 
![이미지 1](https://user-images.githubusercontent.com/68038112/112248970-45de9780-8c9a-11eb-8ea6-5849e41785d5.png)

- 항목 및 설명 : 인쇄 페이지 순서 등록 화면에서 펜 연결 시 아이콘이 연결안된 상태로 보이는 문제입니다. 
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by KiyeonSeo** [comment]
@songkyungha 책임님, 처리 되었습니다. 확인 요청 드립니다.
