### ISSUE TITLE
[Internet Explorer] Internet Explorer에서 접속 시 chrome browser 이동 메세지 표시 안됨(기획 문의)

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#108]
- 버전: 그리다 보드 2.0
- 접속경로 : https://gridaboard-v2-test.web.app/

Internet Explorer에서 접속 시 아무 반응이 없습니다. 
현재 실서버에서 사용 중인 그리다보드(베타) 버전에서는  chrome browser 이동 하라는 안내 메시지 표시됩니다.
![chrome](https://user-images.githubusercontent.com/57121184/112249688-8ab6fe00-8c9b-11eb-9d32-32f08097891a.png)
![Explorer](https://user-images.githubusercontent.com/57121184/112249690-8b4f9480-8c9b-11eb-8ea9-bf687f954cc8.png)

**Comment by KiyeonSeo** [comment]
@minihallo @hwansang 
네오스튜디오에서 아래와 같이 적용되었던 이력이 있습니다. 
적용해주시면 될 듯합니다. 
![image](https://user-images.githubusercontent.com/52436213/112261771-cfe52b00-8caf-11eb-8bcd-0af03bdcccdc.png)

@NeolabAram 수석님, 
예전에 네오스튜디오에 크롬 사용 안내 진행 수석님께서 해주셨죠? 
저 페이지 작업 파일 민희 프로님, 환상 매니저님께 전달 요청 드립니다.

**Comment by NeolabAram** [comment]
작업한 기억이 없습니다..
어디에서 볼 수 있는 페이지 인가요?

**Comment by KiyeonSeo** [comment]
@NeolabAram 
IE 11에서 공유된 링크 열리지 않는 이슈
http://bug.neolab.kr/view.php?id=6129
참고하세요.

**Comment by NeolabAram** [comment]
neostudio가 아니고 share studio에 적용됬던 내용이네요

    var agent = navigator.userAgent.toLowerCase();
    if ( (navigator.appName === 'Netscape' && agent.indexOf('trident') !== -1) || (agent.indexOf("msie") !== -1)) {
      window.location.href = './assets/notsupport';
    }

**Comment by KiyeonSeo** [comment]
@hwansang @minihallo  문수석님 코멘트 확인 후 적용 요청 드립니다.

**Comment by KiyeonSeo** [comment]
@minihallo-neo 프로님,

아직 팝업이 뜨고, 확인 선택 시 페이지를 닫네요. 
![image](https://user-images.githubusercontent.com/52436213/112293251-4a747180-8cd5-11eb-88f7-23c120190343.png)
![image](https://user-images.githubusercontent.com/52436213/112293203-392b6500-8cd5-11eb-8f57-cf3ed691f5ab.png)

**Comment by KiyeonSeo** [comment]
2021.07.21 강제로 페이지 닫기로 처리 완료 확인 (서기연)
