### ISSUE TITLE
[인쇄 페이지 순서 등록] 인쇄 페이지 순서 등록 중 취소 후 재 등록 시도 시 등록안되는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#109]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/odytEbkgWr8
- 항목 및 설명 : 인쇄 페이지 순서 등록 중 취소 후 재 등록 시도 시 동일한 페이지가 아님 pop-up이 출력됩니다. 동일한 페이지 선택했는데도 해당 pop-up이 출력되어 다음 동작으로 넘어가지 않습니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by KiyeonSeo** [comment]
@hwkim000 매니저님, 확인 및 정리 필요합니다.

**Comment by hwkim000** [comment]
현재는 중간에 취소버튼 눌러도 이미 그 페이지는 이미 등록 안료된 페이지여서 next버튼 누르고 등록 안한 페이지부터 등록해야합니다

**Comment by KiyeonSeo** [comment]
대략적으로 고민해보자면, 아래와 같이 정리할 수 있을 것 같습니다. 
어려운 기능인데, 취소했을 때 안내도 없이 취소되다보니... 사용자에게 혼선을 주는 것 같습니다. 

- NCODE포함해서 출력 : 이미 페이지 순서가 등록되어 있어서... 다시 등록할 필요가 없고, 다시 등록하면 기존에 출력한 내용과 상충될 수 있다는 안내 필요
- NCODE A4 출력
  - 취소 버튼 누를 때 매핑된 내용을 취소를 할 수 있다면 취소
  - 취소 버튼 누를 때 매핑된 내용을 취소할 수 없다면, 현재까지 등록된 페이지는 매칭이 완료되었고 남은 페이지에 대해서만 매칭할 수 있다는 안내 필요

**Comment by hwkim000** [comment]
@KiyeonSeo 취소 버튼 없애고 등록 완료 전까지 해당 페이지 이탈 막는 것으로 정리했고, 관련해서 안내 문구 라벨로 표시하는 걸로 요청드리도록 하겠습니다.

**Comment by minihallo-neo** [comment]
취소 버튼 없앴고 여전히 esc로 취소할 수 있긴한데 이때 재등록 안되는 문제는 수정했습니다
