### ISSUE TITLE
[UI] 프린트, 인쇄 페이지 순서 등록, 펜 연결 아이콘 선택 후 취소 시 UI 오류

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#110]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/hukDlyJR8x4
- 항목 및 설명 : 프린트, 인쇄 페이지 순서 등록, 펜 연결 아이콘 선택 후 취소 시 아이콘을 선택하고 있는것처럼 보여지는 문제입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by KiyeonSeo** [comment]
@hwansang 매니저님, 확인 요청 드립니다.

**Comment by songkyungha** [comment]
이전, 다음 페이지 버튼도 동일하게 재현됩니다. 
확인부탁드립니다.

**Comment by hwansang** [comment]
음 제 로컬에서는 그런 오류가 발생하지 않는데 정확히 선택하고 있다는 표현이 무슨 의미인가요? hover나 check 상태가 계속 되어있다는 건가요?

**Comment by songkyungha** [comment]
![이미지 3](https://user-images.githubusercontent.com/68038112/112275888-6ff87f80-8cc3-11eb-867a-018cab192e7f.png)
첨부된 이미지처럼 테두리? 가 계속 보여지고 있습니다. 
다른 부분 선택해야 해당 테두리가 없어집니다.

**Comment by KiyeonSeo** [comment]
@songkyungha 책임님, 처리되었습니다. 확인 요청 드립니다.
