### ISSUE TITLE
[기본 페이지] 그리다 보드 2.0 첫 진입 시 기본 페이지가 생성되는 이슈(기획문의)

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#111]
- 버전: 그리다 보드 2.0
- 접속경로 : https://gridaboard-v2-test.web.app/

그리다 보드 2.0 첫 진입 시 기본 페이지가 생성되는 이슈 입니다. 
현재 그리다보드(베타) https://gridaboard.web.app/ 처럼 기본 페이지 비활성화 되어야 합니다. 
필기 시 페이지 생성 되어야 합니다. 

또는 펜 연결 후 필기 시 기본 페이지(1페이지)에 필기 되어야 합니다.
현재는 기본 페이지가 생성되고 있고,  펜으로 필기 시 새로운 페이지(2페이지)가 생성됩니다. 

![제목 없음](https://user-images.githubusercontent.com/57121184/112259002-d8873280-8caa-11eb-8269-c4b4b2878daf.png)

**Comment by KiyeonSeo** [comment]
@minihallo #99 와 연계되는 이슈 입니다. 
기본 페이지 비활성화 처리 가능 여부 검토 요청 드립니다.
