### ISSUE TITLE
[UI] 펜 굵기 선택 아이콘 4단계부터 이미지 잘리는 이슈(그림첨부)

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#112]
- 버전: 그리다 보드 2.0
- 접속경로 : https://gridaboard-v2-test.web.app/

펜 굵기 선택 아이콘 4단계부터 이미지 잘리는 이슈입니다.
![제목 없음](https://user-images.githubusercontent.com/57121184/112268972-1d1aca00-8cbb-11eb-9951-3fd33e1b6eee.png)

**Comment by KiyeonSeo** [comment]
@yeji-qa 책임님, 처리되었습니다. 확인요청 드립니다.
