### ISSUE TITLE
PDF 수정 후 다른이름으로 저장 > 새로고침 후 수정한 PDF 불러온 후 원본 PDF 불러오기 시도 시 동작 문의

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#113]
- 발견 일시 : 2021.03.24
- 화면 : https://youtu.be/ZsF1BVpDLn8
- 항목 및 설명 : A.PDF 파일 불러오기 > 임의로 수정 후 B.PDF로 저장 > 페이지 새로고침 후 B.PDF 불러오기 후 A.PDF 불러오기 시 이미 등록된 PDF가 존재합니다. pop-up 출력되고 있습니다. pdf 파일명과 내용 수정을 했는데 동일한 PDF로 보는게 정상 동작인지 기획 확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by hwkim000** [comment]
@minihallo-neo 해당 내용 관련하여 기술 설명 부탁드립니다.
@KiyeonSeo 이 이슈 기획적으로 문제 없는지 확인부탁드립니다.

**Comment by Minkyum-Kim** [comment]
기술적으로 해당 파일을 저장할때 같이 저장되는 fingerprint(디지털 지문)값이 동일하여 발생하는 문제입니다. 
(원칙적으로 PDF fingerprint 는 "파일이 생성된 시점의 파일 내용을 기반으로 하는 영구 식별자" 입니다)

기술적으로 fingerprint 는 고유하지 않을 수 있기 때문에 fingerprint 만으로 동일 파일을 검사하는것을 변경 해야 할것 같습니다.

참고(https://www.seanh.cc/2017/11/22/pdf-fingerprinting/)

**Comment by KiyeonSeo** [comment]
책임님, 
기술적으로는 같은 파일(페이지)라고 볼 수 밖에 없습니다. 
해당 이슈는 클로즈 해주십시오!
@songkyungha

**Comment by songkyungha** [comment]
코멘트 확인하였습니다. 
이슈 close 하겠습니다.
