### ISSUE TITLE
[새로고침] 펜 연결 후 새로고침 시에도 '페어링 됨'으로 출력되는 이슈

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#114]
발견 일시 : 2021.03.25

항목 및 설명 : 

새고로침으로 펜 연결이 끊어졌는데도 펜 연결 시도시 '페어링 됨'으로 출력되는 이슈입니다.
![페어링](https://user-images.githubusercontent.com/61952421/112400846-97dff580-8d4c-11eb-8535-441f7aa6d581.png)

재현 경로 : 
펜 연결 후 새로고침 > 펜 연결 UI 클릭 > 펜 연결 상태 확인

발생 빈도 : 항상
앱버전 : 그리다보드 2.0
등록자 : 함종덕

**Comment by hwkim000** [comment]
해당 창은 브라우저 시스템 창으로 제어가 불가능하고 '페어링됨'이란 표시는 해당 블루투스 기기가 연결된 이력이 있다는 뜻으로 연결되어 있다는 안내는 아닙니다. 참고부탁드립니다.
