### ISSUE TITLE
[지우개] 지우개 기능 개선 검토 요청 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#115]
발견 일시 : 2021.03.25

항목 및 설명 :

지우개 동작시 획이 매끄럽게 지워지지 않는 것같은 이슈입니다.
기능 개선의 여지가 있는지 검토 부탁드립니다. 

https://drive.google.com/file/d/12z0FaEVgDunR0MsQTcC7ixcFqFpTds8N/view?usp=sharing

발생 빈도 : 항상
앱버전 : 그리다보드 2.0
등록자 : 함종덕

**Comment by hwkim000** [comment]
현재는 스트롴 단위로 한 획씩 지워지게 되어있습니다. 추후 선택 영역만 삭제될 수 있는지 확인부탁드립니다.
@minihallo-neo

**Comment by KiyeonSeo** [comment]
2021.07.28 처리 완료 확인 (서기연)
