### ISSUE TITLE
[메뉴 버튼] 그리다 보드 2.0 첫 진입 시 저장하기 버튼이 활성화 되어 있는 이슈

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#118]
- 버전: 그리다 보드 2.0
- 접속경로 : https://gridaboard-v2-test.web.app/

그리다 보드 2.0 첫 진입 시 저장하기 버튼이 활성화 되어 있습니다.
저장할 수 있는 데이터가 없기 때문에 버튼을 눌러도 반응이 없습니다. 

데이터가 생성된 이후부터 활성화 되어야 합니다. 
![제목 없음](https://user-images.githubusercontent.com/57121184/112405301-5b64c780-8d55-11eb-89af-f38da9f3f8d0.png)

**Comment by minihallo-neo** [comment]
비활성화 처리했습니다
