### ISSUE TITLE
[페이지 회전] 스트로크가 있는 페이지를 빠르게 회전 시 이슈 (불규칙이슈) / 페이지 회전 기능 개선 검토 요청 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#123]
발견 일시 : 2021.03.25

항목 및 설명 :

스트로크가 있는 (많을 수록 심해지는 것으로 추정됩니다.) 페이지를 빠르게 회전할 경우 가끔씩 아래 이미지와 같이 페이지가 깨지는 현상이 확인됩니다. 

추가로 스트로크가 없는 페이지를 회전시킬때도, 이미지가 잠시(1초) 확대되었다가 회전되는 것으로(100%) 확인되는데 해당 부분 조금 더 매끄럽게 전환되도록 개선할 수 있는지 검토 부탁드립니다. 

![페이지전환](https://user-images.githubusercontent.com/61952421/112413162-0d56c080-8d63-11eb-8512-9b1c196cdbf2.png)

발생 빈도 : 항상
앱버전 : 그리다보드 2.0
등록자 : 함종덕

**Comment by hwkim000** [comment]
@neoJD 화면 회전 시 배경 회전 지연은 이번 버전에서는 이슈 크지 않을것 같아 대표님과 의논 후 보류한 것으로 알고 있습니다.
@minihallo-neo 추후 개선 가능한 사항인지 확인 부탁드립니다.
@hwansang 가로 회전 시 해상도 깨지는 이슈 확인부탁드립니다.

**Comment by KiyeonSeo** [comment]
#234 동일이슈로 #234에서 관리할 예정임, 
이 이슈는 클로즈하겠습니다.
