### ISSUE TITLE
[기획][제안] 펜 연결 해제시 Alert 출력 기능 추가 검토 요청드립니다.

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#125]
항목 및 설명 :  

그리다보드 사용 중 (어떠한 이유로) 펜 연결이 끊어질 경우 '펜 연결이 해제 됨' Alert를 사용자에게 보여주는 기능에 대한 의견 드립니다. 

특히 펌웨어를 통해 BT 연결/해제 알림을 받을 수 없는 DIMO / F80(LAMY) 같은  경우,  펜 연결이 해제된 것을 인지하지 못한 채 필기를 하는 경우도 종종 발생할 수 있을 것이라고 생각됩니다.  

추후 업데이트 버전에 적용될 수 있는지 기획/개발부분 검토 요청 부탁드립니다. 

등록자 :  함종덕

**Comment by hwkim000** [comment]
@neoJD 해당 내용 및 기타 안내(Alert) 이번 릴리즈 버전에 시간 관계상 제외되었으며, 추후 업데이트 버전에 추가할 예정으로 기획서에 반영되어 있는 점 참고부탁드립니다. 제안 감사합니다.

**Comment by KiyeonSeo** [comment]
@minihallo 

책임님, 

펜 연결이 해제되었다는 안내창 추가 요청 드립니다. 

문구 : "펜 연결이 끊어졌습니다. \n 펜 확인 후 다시 연결해주세요."

**Comment by minihallo-neo** [comment]
펜이 여러개 붙어있는 상황에서는 어떻게 할까요?

**Comment by minihallo-neo** [comment]
현재 쓰고있는 펜에 한해서 연결이 끊어질 경우 alert를 보여주도록 추가했습니다.

**Comment by KiyeonSeo** [comment]
2021.07.21 처리 완료 확인 (서기연)
