### ISSUE TITLE
현,구버전 연결 버튼 추가 및 url 비활성 안내

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#128]
- 요청 일시 : 2021.03.26
- 위치 : 테스트 페이지와 기존 버전 페이지 내 우측 상단
- 화면 : 캡처 포함
- 항목 및 설명 : 필름 테스터를 위해 테스트URL을 배포했는데 기존 버전에 대한 니즈가 있을 것이라 생각돼 두 버전을 연결하는 버튼이 필요합니다. 버튼 위치는 각 페이지 우측 상단으로 아래 화면 참고부탁드리며, https://gridaboard.web.app/ 비활성에 대한 안내가 필요합니다. 이와 관련하여 팝업이 좋을지 버튼 옆 텍스트 안내가 좋을지에 대한 논의가 필요합니다.
- 버전 : 
1. https://gridaboard.web.app/
2. https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![그림1](https://user-images.githubusercontent.com/80931389/112582186-02bb2a80-8e3a-11eb-99cf-4f57ab027b0c.png)
![image (35)](https://user-images.githubusercontent.com/80931389/112582212-03ec5780-8e3a-11eb-9ca6-7b2fadfa0a34.png)

**Comment by hwkim000** [comment]
@minihallo-neo 말씀드린 https://gridaboard.web.app/ 좌측 상단에 들어갈 안내 문구입니다.
- 지금 보시는 페이지는 그리다보드 구버전으로 추후 서비스를 종료할 예정입니다. 
새롭게 개편된 최신버전 그리다보드를 통해 더욱 다양한 활용을 경험하세요!

**Comment by KiyeonSeo** [comment]
@minihallo 민희 프로님, 문구 조금 더 업데이트 하였습니다. 

지금 보시는 페이지는 그리다보드 구버전으로 2021년 4월 중 서비스를 종료할 예정입니다.
새롭게 개편된 최신버전 그리다보드를 통해 더욱 다양한 활용을 경험해보세요!
