### ISSUE TITLE
[기획 문의] 필기펜/형광펜 교차 사용시 펜 굵기 표현기획 문의] 필기펜/형광펜 교차 사용시 펜 굵기 표현

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#129]
발견 일시 : 2021.03.26
위치 : 펜 설정

항목 및 설명 : 

필기펜과 형광펜 굵기가 서로 다른 상태에서 펜 전환 시 굵기가 직전에 사용하던 펜의 굵기로 유지되는 것으로 표시되고 있습니다.  필기펜 / 형광펜 서로 전환 시 '펜 설정 > 펜 굵기' 에서 각각 설정된 펜 굵기로 변경되어 출력되도록 변경한다면, 유저들이 조금 더 이용하기 편할 것 같습니다. 기획 검토 부탁드립니다. 

발생 기기(OS) : Desktop / WIN 10(2004)

발생 빈도 : 항상

버전 : https://gridaboard-v2-test.web.app/

등록자 : 함종덕

**Comment by KiyeonSeo** [comment]
@minihallo 프로님, 개선이 가능한 부분인지 검토 요청 드립니다. 
3월내에 적용이 필요한 기능은 아니지만, 4월 업데이트에 적용가능하다면 적용하고자 합니다.

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 확인 부탁드립니다

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 팀장님, 테스트 서버(https://gridaboard-v2-test.web.app/)에 배포 완료 했습니다. 확인 부탁드립니다

**Comment by minihallo** [comment]
교차 사용시 굵기 표현을 개선하려면 드랍다운 메뉴가 하나 더 필요해보이고 따라서 svg icon도 더 필요합니다. icon만 있으면
개선 작업은 그렇게 오래 걸리지 않아요.

2021년 3월 26일 (금) 오후 3:14, KiyeonSeo ***@***.***>님이 작성:

**Comment by KiyeonSeo** [comment]
(2021.04.22 서기연) 펜/형광펜 두께 별도 적용 처리 완료 확인
