### ISSUE TITLE
[스트로크가 찍히고 나서 tracer가 남아있는 문제]

### ISSUE THREAD

**Issue by hwansang** [neostudio-team/GridaBoard2#13]
[이슈 내용]

penUp 이후에 마지막 스트로크 지점에 tracer가 남아있습니다.

![image](https://user-images.githubusercontent.com/75828099/104166926-e1ec5700-543e-11eb-851b-6eb5497b9b8b.png)

발생 기기 : web
발생 빈도 : 항상
버전 : 2.0

**Comment by minihallo-neo** [comment]
해결함
