### ISSUE TITLE
[제안]인쇄페이지 선택 관련 (PDF의 일부 페이지 작업 관련)

### ISSUE THREAD

**Issue by nhw0223** [neostudio-team/GridaBoard2#132]
a)총 18페이지의 PDF를 업로드?(불러오기)한 후 1페이지만 출력
![image (13)](https://user-images.githubusercontent.com/80810913/112601528-e75e1880-8e55-11eb-8cc7-c3d39cc5bf36.png)

b) 매칭작업을 위해 진행
![image (14)](https://user-images.githubusercontent.com/80810913/112601571-f5ac3480-8e55-11eb-9cee-4267e2157cc5.png)

c)1페이지만 출력했기에 2페이지 진행시 창 닫음
![image (15)](https://user-images.githubusercontent.com/80810913/112601628-052b7d80-8e56-11eb-9b54-0ce87e3c0288.png)

d)1페이지에 필기를 하면 36페이지로 전체페이지수가 증가하면서 19페이지로 필기가 됨
![image (16)](https://user-images.githubusercontent.com/80810913/112601675-12e10300-8e56-11eb-8abd-6d8e8ae694e0.png)

기존 그리다보드도 동일하였기에 관련 고객님 문의시
18페이지 전부를 출력하시거나
1페이지외의 나머지 2~18페이지는 Ncode있는 페이지에 출력으로 권유하거나
PDF를 필요한 페이지(1페이지)만큼만 별도 수정 후 작업진행 권유하였습니다.

출력도 고객님께서 선택할 수 있기에 인쇄물 등록도 고객님께서 선택할 수 있도록 제안드립니다.

**Comment by minihallo-neo** [comment]
해결되었습니다.
