### ISSUE TITLE
인쇄옵션 문구 수정

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#134]
- 요청 일시 : 2021.03.26
- 위치 : 프린트 > 인쇄 옵션
- 화면 : 캡처 포함
- 항목 및 설명 : 인쇄옵션 화면에 문구 수정부탁드립니다.
1. 인쇄 옵션 -> 스마트펜용 인쇄 옵션
2. PDF로 저장 -> 재인쇄용 PDF 저장
- 버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/112605817-0ca15580-8e5b-11eb-86b4-992d2625b67a.png)

**Comment by minihallo-neo** [comment]
수정했습니다. 감사합니다.
