### ISSUE TITLE
[저장하기] Landscape / Portrait 섞어 사용 후 pdf로 저장시 획이 세로뷰 기준으로 저장되는 이슈 발생

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#135]
발견 일시 : 2021.03.29
위치 : 저장하기

항목 및 설명 :

가로뷰와 세로뷰를 섞어서 필기 작성 후 pdf로 저장 > 확인 시 발생하는 이슈입니다. 

https://user-images.githubusercontent.com/61952421/112789334-d3a1f480-9097-11eb-902b-47bcc461e0c8.mp4

발생 기기(OS) : desktop / win10 (2004)

발생 빈도 : 항상

버전 : https://gridaboard-v2-test.web.app/

등록자 : 함종덕

**Comment by neoJD** [comment]
마우스로 그린 획이 아닌 실제 펜으로 테스트해도 동일한 결과를 확인할 수 있습니다.

**Comment by minihallo-neo** [comment]
수정했습니다. 감사합니다.
