### ISSUE TITLE
[단축키] 포인터 단축키 'T' 동작하지 않는 현상

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#136]
발견 일시 : 2021.03.29
위치 : 페이지뷰

항목 및 설명 :

포인터 단축키 'T' 동작하지 않는 현상입니다. 

발생 기기(OS) : Desktop / WIN 10 (2004)

발생 빈도 : 항상

버전 : https://gridaboard-v2-test.web.app/

등록자 : 함종덕

**Comment by minihallo-neo** [comment]
수정했습니다. 감사합니다.
