### ISSUE TITLE
[불러오기]불러오기시 열기 팝업이 안 뜹니다.

### ISSUE THREAD

**Issue by nhw0223** [neostudio-team/GridaBoard2#137]
![불러오기오류](https://user-images.githubusercontent.com/80810913/112920878-c989ff80-9144-11eb-9631-5307e532f527.png)
불러오기를 눌러도 구버전 처럼 열기 팝업이 안 뜨기에 PDF를 추가할 수가 없습니다.
현재 고객 문의 1건 / 재택 근무하는 서포터분도 동일한 증상 <크롬 브라우져 확인>

![구버전불러오기](https://user-images.githubusercontent.com/80810913/112920962-ec1c1880-9144-11eb-97de-8b39bfbd7505.png)
구버전 불러오기는 정상이기에 구버전으로 사용권유 드린 상태입니다.
확인 부탁드립니다.

**Comment by minihallo-neo** [comment]
불러오기를 누르면 드롭다운 메뉴로 파일 업로드, 데이터 불러오기가 나오고 거기서 파일 업로드를 누르면 pdf를 추가할 수 있습니다. 혹시 드롭다운 메뉴가 안뜬다는 말씀인가요? 지금 테스트 해봤을 땐 정상동작합니다.

**Comment by nhw0223** [comment]
불러오기를 눌러도 파일업로드,데이터불러오기가 안 뜬다고 합니다.
![image](https://user-images.githubusercontent.com/80810913/112948926-9c087a80-9173-11eb-8ba9-258779fdd337.png)

저도 제 PC에서는 잘 활용이 됩니다.

고객님외에도 서포터분 노트북에서 재현되는데 현재 재택업무중입니다.
요청주시면 노트북들고 회사 출근 요청 가능은 합니다.
확인 후 의견부탁드려요~ (번외로 노트북에서 화면 잘림은 여전하던데 맞나요? 만약 개선 된거라면 해당 노트북 재현 시료는 바로 보여드릴 수 있습니다.)

**Comment by minihallo-neo** [comment]
회사 노트북으로 테스트 해봐도 문제없는데 쿠키 삭제 후에 시도해보시라고 전달해주시겠어요? 화면 잘림은 [페이지뷰] 페이지 해상도 관련 이슈 (하단 부 잘림) 이 이슈 말씀하시는거라면 수정됐다고 합니다.

**Comment by nhw0223** [comment]
쿠키 삭제 해도 동일하다고 합니다.
재택인원 노트북 3대 쿠키삭제 후에도 증상 개선 안됨 / 하단 뷰 잘림 노트북 증상재현되는 건 1대(14층) 있습니다.
명일 시료 필요시 말씀주세요~

**Comment by Minkyum-Kim** [comment]
불러오기 기능 통합 이후로, 같은 증상이 발생하는지 한번 확인 부탁드립니다.

**Comment by nhw0223** [comment]
해당 이슈 개선되었습니다~^^ 이슈 종결할게요~ 고생 하셨습니다~
