### ISSUE TITLE
[펜에서 color 값 변화를 주고 형광펜으로 변경 시 적용이 안되는 문제]

### ISSUE THREAD

**Issue by hwansang** [neostudio-team/GridaBoard2#14]
[이슈 내용]

펜과 형관펜의 color가 독립적으로 영향을 주지 않아 colorButton과는 상관없이 따로 색상이 지정되게 됩니다.

<펜 타입 - 검은색>
![image](https://user-images.githubusercontent.com/75828099/104256419-91b4d980-54be-11eb-99b1-650f1a5a4517.png)
![image](https://user-images.githubusercontent.com/75828099/104256402-89f53500-54be-11eb-9892-e28101d4d76c.png)

<펜 타입 - 빨간색>
![image](https://user-images.githubusercontent.com/75828099/104256503-b0b36b80-54be-11eb-9286-cc6c8fd1232d.png)
![image](https://user-images.githubusercontent.com/75828099/104256517-b90ba680-54be-11eb-9d7f-f5a931fd5f9e.png)

<형광펜 타입 - 버튼은 빨간색 지정 상태>
![image](https://user-images.githubusercontent.com/75828099/104256585-d80a3880-54be-11eb-9b7e-0a1f4b7f6554.png)
![image](https://user-images.githubusercontent.com/75828099/104256572-d2acee00-54be-11eb-824f-3ec80995e524.png)

발생 기기 : web
발생 빈도 : 항상
버전 : 2.0

**Comment by minihallo-neo** [comment]
해결
