### ISSUE TITLE
전체 메뉴 위치 조정

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#140]
- 발견 일시 : 2021.03.31
- 위치 : 툴팁, 도움말, 드롭다운
- 화면 : 캡처 포함
- 항목 및 설명 : 전체 메뉴들 툴팁, 도움말 박스 및 드롭다운 박스 위치의 조정이 필요해보입니다.
- 발생 기기 : LG gram
- 발생 빈도 : 항상
- 버전 : https://gridaboard.web.app/
- 등록자 : 김혜원
 
[화면]
![image](https://user-images.githubusercontent.com/80931389/113077937-1df8b200-920d-11eb-9a75-477646bcb86e.png)
![image](https://user-images.githubusercontent.com/80931389/113082598-c01c9800-9215-11eb-8148-da6493672265.png)

**Comment by Minkyum-Kim** [comment]
크롬 줌을 건드릴 경우 발생하는 문제인데, 어느정도 코드를 통해 해소했으나, 줌이 너무 커질 경우(200% 오버) 위치 변화가 일어납니다. 기능적으로 크롬 줌을 막았으나, 설정을 통해 강제로 바꿀 경우 발생하는 문제입니다.
