### ISSUE TITLE
[프린트] 페이지 윤곽 표시

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#141]
- 발견 일시 : 2021.03.31
- 위치 : 프린트 > 페이지 윤곽 표시
- 화면 : 캡처 포함
- 항목 및 설명 : 프린트 설정에 페이지 윤곽 표시 도움말을 보니, 분할 인쇄 시 필요한 기능인거 같은데 분할 인쇄 옵션 빠진 현재 필요한 기능인지 의문이 들어서요. 논의 부탁드립니다.
- 발생 기기 : LG gram
- 버전 : https://gridaboard.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/113079099-63b67a00-920f-11eb-8f53-2cfcbbd6286b.png)

**Comment by KiyeonSeo** [comment]
#252 와 연계 이슈
