### ISSUE TITLE
[펜등록버튼] Windows에서 Bluetooth 장치 off 상태에서 펜 등록 버튼 선택 시 아무런 반응이 없는 이슈(동영상첨부)

### ISSUE THREAD

**Issue by yeji-qa** [neostudio-team/GridaBoard2#142]
-버전: 그리다 보드 2.0
-접속경로 : https://gridaboard-v2-test.web.app/
-동영상: https://youtu.be/7GWxJ8lcWM4

Windows에서 Bluetooth 장치 off 상태에서 펜 등록 버튼 선택 시 아무런 반응이 없습니다.
그리다 보드 구버전 경우 "블루투스 연결 실패 / 블루투스 어댑터를 찾을 수 없습니다" 라는 경고 팝업을 보여줍니다.
사용자에게 해당 경고 팝업 필요합니다.

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 

안내 메세지는 아래 내용으로 적용 요청 드립니다. 

"이 기기에서 블루투스를 사용할 수 없어, 네오스마트펜을 연결할 수 없습니다. \n블루투스 동글을 설치하신 후 다시 시도해주세요."

**Comment by Minkyum-Kim** [comment]
해당 이슈는 종료하겠습니다.
