### ISSUE TITLE
PDF 등록 안됨

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#146]
- 기존 그리다보드에는 등록되는 PDF 파일인데, 새 버전에서는 등록안됩니다. (등록한 후 7분째 대기중)
- 파일 : 22장, 530KB파일
[2018_단체참가 해외전시회 바우처 기업 선정결과(KOTRA-중소기업중앙회 통합).pdf](https://github.com/neostudio-team/GridaBoard2/files/6247985/2018_.KOTRA-.pdf)

**Comment by minihallo-neo** [comment]
어떤 환경에서 발생하는 이슈인가요? 제 노트북에서는 4초만에 등록됩니다.

**Comment by KiyeonSeo** [comment]
@minihallo LG 노트북이고 Win 10, 크롬입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈는 종료하겠습니다.
