### ISSUE TITLE
기존 사용자(선생님)들을 위해 V1 운영 계획 수립 필요

### ISSUE THREAD

**Issue by sexyflash-neo** [neostudio-team/GridaBoard2#147]
선생님 중 일부가 익숙해 질려고 하면 바뀌고 바뀌고 6번을 경험하여 피로감이 있다고 합니다.
이에 대해서 다음과 같은 옵션을 고민할 수 있을 것 같습니다.

1. 구 버전 바로가기 유지
2. v1 도메인 이쁘게 하나 따기 app.gridaboard.io/v1
3. 나중에 index 페이지가 생겼을 때, 그리다보기 로그인하기 아래 "구 버전 사용하기" 버튼 삽입

고민이 필요합니다.

**Comment by KiyeonSeo** [comment]
@sexyflash-neo 
센터장님, 요건... 제가 맡기 전에 어떤 업데이트들이 있어서, 어떤 부분들을 힘들어하셨는지 고객지원실에 말씀 들어볼 필요가 있을 것 같습니다. 
남형우 책임님께 문의드려 보겠습니다.

**Comment by KiyeonSeo** [comment]
이 항목은 업데이트 시 아래 항목에 맞추어 운영 예정입니다. 

- 사용자의 피로감이 크지 않도록 업데이트 
- 고객과의 접점에 있는 유관부서 (고객지원팀, B2C유통사업본부, 영업본부)에 업데이트에 대한 항목 미리 공유할 것 (설명회 등)
- 업데이트된 기능 오픈전에 유관부서에서 함께 확인/테스트 할 수 있도록 제공
