### ISSUE TITLE
파일 여러개 불러오기 할 경우 화면 조절이 따로 적용되지 않음

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#148]
발견일시: 21.04.12

설명:  파일 여러개를 동시에 불러오기했을때 한 페이지만 확대를 해도 다른 페이지까지 모두 동일한 비율로 확대가 됩니다.

스크린샷: 

![캡처](https://user-images.githubusercontent.com/80810905/114351529-b3009100-9ba5-11eb-9398-4244f7b27171.PNG)
![캡처2](https://user-images.githubusercontent.com/80810905/114351533-b431be00-9ba5-11eb-80c6-8cc66e5048cf.PNG)

등록자:송은서

**Comment by nhw0223** [comment]
해당 상태에서 필기를 하면 좌표가 어긋나고 글자 사이즈가 다르게 화면에 표현되는 이슈도 발생 됩니다.

**Comment by minihallo-neo** [comment]
화면 조절은 페이지별로 되지 않으며 필기 좌표가 어긋나는 것은 고쳐진 것으로 확인했습니다.
