### ISSUE TITLE
PDF파일 불러오지 않으면 필기가 되지 않음

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#149]
발견일시:21.04.12

설명: PDF 파일을 불러오지 않고 필기하면 'PDF를 등록하거나 펜을 사용해서 페이지를 생성해주세요'라는 문구가 뜨면서 필기가 되지 않습니다. 구버전에서는 PDF를 불러오지않은 상태에서도 필기가 되는데 기획의도인지 궁금합니다!

스샷:
![그리다구버전](https://user-images.githubusercontent.com/80810905/114350723-8ef08000-9ba4-11eb-8b47-4af208619f24.PNG)
![pdf등록 펜 사용](https://user-images.githubusercontent.com/80810905/114350730-9152da00-9ba4-11eb-9f47-49ab777b422c.PNG)

등록자:송은서

**Comment by eunsuh-song** [comment]
마우스로 한번 긋고난 뒤 필기하면 입력되기는 합니다!

**Comment by minihallo-neo** [comment]
혹시 plate에 쓰셨나요? plate나 film에 쓴 경우에는 기획 의도입니다.
