### ISSUE TITLE
[기획] A.grida 파일 불러온 후 B.grida 파일 불러오기 > 다시 A.grida 파일 불러오기 시 동작 문의 

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#154]
- 발견 일시 : 2021.04.19
- 화면 : https://youtu.be/5YWSCDm61hY
- 항목 및 설명 : A.grida 파일 불러오기 후 B.grida 파일 불러오기 > 다시 A.grida 파일 불러오기 시 이미 등록된 PDF가 존재합니다. pop-up 출력되는 문제입니다.
(A노트에서 필기 후 저장 > 새로고침, B노트에서 필기 후 저장 > 새로고침 하였습니다.)
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by minihallo-neo** [comment]
오류 동작이 맞고 수정했습니다. 감사합니다!
