### ISSUE TITLE
[다국어] 영어, 일본어, 중국어(번체) > 도움말 선택 시 텍스트 미출력

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#155]
- 발견 일시 : 2021.04.19
- 화면 : 
![이미지 1](https://user-images.githubusercontent.com/68038112/115171688-8ba64880-a0fe-11eb-9136-fb81e3020f67.png)

- 항목 및 설명 : 언어 변경 후 도움말 선택 시 텍스트가 출력되지 않는 문제입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by Minkyum-Kim** [comment]
해당 문제는 현재 번역본이 오지 않아서, 해당 언어로 된 텍스트가 공백으로 들어가 있어서 발생하는 이슈로, 번역본이 도착하여 엑셀에 입력이 완료되면 자동으로 해결될 문제입니다.

**Comment by songkyungha** [comment]
중국어 번체 > 펜 연결하기 부분 텍스트 출력되지 않고 있습니다. 
+만 출력되고 있습니다.
확인 부탁드립니다.

**Comment by Minkyum-Kim** [comment]
마찬가지로 번역이 도착하지 않아, 아직 입력이 되어있지 않은 이슈입니다

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님, 중문 번체 수급이 안된 경우는 영문으로 노출 요청 드립니다.

**Comment by Minkyum-Kim** [comment]
수정후 배포 완료했습니다.
