### ISSUE TITLE
[버튼] BASIC, 화면 배율 버튼 선택되지 않는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#159]
- 발견 일시 : 2021.04.19
- 화면 : https://youtu.be/_mS86RXc_PY
- 항목 및 설명 : BASIC, 화면 배율 버튼 선택이 안되고 있습니다. 비활성화인 상태입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by Minkyum-Kim** [comment]
죄송합니다. 확인하고 수정하였습니다. 저장하기와 연계된 문제였습니다.
