### ISSUE TITLE
[저장하기] '.' 파일명 저장시 발생되는 증상

### ISSUE THREAD

**Issue by nhw0223** [neostudio-team/GridaBoard2#169]
발견 일시 : 2021.04.21
화면 :
![image](https://user-images.githubusercontent.com/80810913/115500427-3740cb80-a2ac-11eb-84e3-3594f3bd5469.png)

![image](https://user-images.githubusercontent.com/80810913/115500024-81757d00-a2ab-11eb-92a9-9ff4aba411d3.png)

항목 및 설명  : 그리다 저장하기 진행시 파일명을 '......' 방식 ( . 만이루어진 파일명) 으로 저장하니 좌측 하단처럼 저장이 되었고
해당 파일을 불러올 수가 없었습니다.

발생빈도: 항상

등록자: 남형우

**Comment by Minkyum-Kim** [comment]
해당 문제는 크롬 자체에서 다운로드 받는 파일 이름 앞의 .을 전부 제거하는 것과, 프로그램 내에서 .grida를 붙여주는 동작이 엉키면서 발생하는 문제입니다.
ex:  
(사용자 입력) ... =>(코드상에서 .grida를 붙여줌) ....grida () => (크롬에서) grida
=>(크롬에서 확장자 없으니 강제로 붙여줌) grida.json

이런 과정을 통해서 grida.json이라는 파일이 만들어 지는데, 저희는 현재 json파일을 지원하지 않기때문에 다시 읽을 수 없는 형태가 됩니다. 

@KiyeonSeo 이 부분은 정책적으로 저장시 파일 이름 앞부분에 .을 이용하지 못하게 하던가 하는 방식으로 처리해야 할 것 같습니다.

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님, 아래와 같이 정책 정리합니다!!! 
혹, 문제 있는 부분 말씀주세요. 

- 파일명 설정가능 문자 : 텍스트(국문,영문,일문,중문,숫자,+,_,-), 공백, . 
- 공백과 .으로 입력값 시작 불가
- 텍스트(국문,영문,일문,중문,숫자,+,_,-)이 입력된 상태에서만 텍스트 다음에 공백값과 . 입력 가능함

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 
기능을 추가하기 앞서 해당 부분에 띄울 경고문이 필요합니다.

1. 파일명이 공백 혹은 점으로 시작할 수 없습니다.
2. 파일명에는 알파벳, 한글, 일어, 한자, 숫자, +-_ . 만 이용할 수 있습니다.

**Comment by Minkyum-Kim** [comment]
이슈 종료 하겠습니다.
