### ISSUE TITLE
[오류]스마트플레이트로 필기시 코드가 튀는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#170]
발견일시: 21.04.21

설명:  스마트 플레이트로 그리다보드에 필기시 코드가 지속적으로 튑니다. 플레이트를 바꿔서 시도해봤으나 증상 동일하게 반복됐으며 코드가 튀는 위치또한 같았습니다.

스크린샷: 
![스샷](https://user-images.githubusercontent.com/80810905/115503569-97863c00-a2b1-11eb-9833-4bada85a5614.PNG)

발생빈도: 지속적으로 발생

**Comment by minihallo-neo** [comment]
종료되었던 이슈입니다.
