### ISSUE TITLE
[오류]스마트플레이트로 작성하고 저장한 그리다 파일 불러오기가 안됨

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#172]
1.발견일시: 21.04.21

2.설명: 스마트플레이트로 작성하고 저장한 GRIDA 파일을 불러오기 했을때 필기한 내용이 안 보입니다. 마우스로 필기하고 GRIDA 파일 저장후 불러오기 했을때는 문제가 없는걸 보면 스마트플레이트 관련 이슈 같습니다.

5.발생빈도: 계속

**Comment by minihallo-neo** [comment]
스마트 플레이트에 쓴 상태에서 pdf로 저장했을 때 스트로크가 안보이거나 다른 위치에 있는 것과 동일한 증상입니다. 수정해서 배포했습니다.
