### ISSUE TITLE
[문구변경] 블루투스 기능 없는 기기 안내

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#183]
### 사용자가 조금 더 명확하게 인지하게 제공하기 위해 문구 수정함 
https://docs.google.com/spreadsheets/d/1y3mHS1A27bzKke3ApuFDmWTBzyAnTH66dO-YKPlmnZA/edit#gid=1135475639

- string name : noBluetoothAdapter

- 기존 : 이 기기에서 블루투스를 사용할 수 없어, 네오스마트펜을 연결할 수 없습니다. \n블루투스 동글을 설치하신 후 다시 시도해주세요. 

- 변경 : 이 기기에 블루투스 기능이 없어, 네오스마트펜을 연결할 수 없습니다. \n블루투스 동글을 장착하신 후 다시 시도해주세요.

**Comment by Minkyum-Kim** [comment]
엑셀에 데이터에는 아직 변경 하지 않은건가요?

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 업데이트 했습니다. 

https://docs.google.com/spreadsheets/d/1y3mHS1A27bzKke3ApuFDmWTBzyAnTH66dO-YKPlmnZA/edit#gid=1135475639

**Comment by KiyeonSeo** [comment]
@neoJD 책임님... 혹... 블루투스 장착되지 않은 기기가 있다면 확인 요청 좀 드려도 될까요???

**Comment by neoJD** [comment]
@KiyeonSeo 동글 제거 후 스트링 확인 결과 '변경된 스트링'으로 정상 출력됨을 확인하였습니다. 

 ** 추가) 위 스트링 확인 중에 확인된 내용으로 동글 장착 후 별도의 '새로고침' 또는 그리다보드 완전 종료 후 재접속으로만 동글 연결을 인식하는 것을 확인하였습니다. 별도 이슈 등록이 필요하다면 말씀해주세요! 

![스트링확인](https://user-images.githubusercontent.com/61952421/126592136-e8bffe54-5c10-4530-9cab-f74b20de28f1.png)

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, 확인 감사합니다. ^^

추가로 발견해서 말씀주신 동글 인식은 크롬/기기 이슈라... 대응할 수 없는 이슈입니다. ^^;;;;
