### ISSUE TITLE
[정책] 그리다보드 펜 정책

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#186]
- 그리다보드에서 사용가능한 펜은 BTID를 white list로 관리해서 정책 적용 필요함
- 펜 white list를 서버에서 관리 (네오 스튜디오는 firebase에 올려두고 관리중)
- 펜 추가되는 시점마다 정책 업데이트 필요
- 추후 정책상 그리다보드를 사용 못하게 하거나, 일부 기능 제약이 필요할 수 있음

**Comment by KiyeonSeo** [comment]
### 그리다보드에서 사용가능한 펜 목록 (BTID)

Smartpen dimo_d
Dimo_ZEQUENZ
dimo_KISA
NWP-F50-DP_d
KYOWON-SMARTPEN
Neosmartpen_M1
NeosmartpenLINE
F50-NLT_d
Mbest_smartpenF
F50-monami_e
SPP: NeosmartpenWS_d
LE : NeosmartpenWS_LE_d
F51_InformDS_d
F51_biz_d
Neosmartpen_M1+
F51-SC_e
F51_FB_d
F51_LC_d
CarbonCopyPen_d
Mbest_smartpen4
YANGJISA_BK
Pen+ Ellipse
LAMY_safari
AIITP_d
Smart_SSEN
ACE-F121_d
F121-NBX
F121-EL_e
NeosmartpenHL_e
NeosmartpenIC_d

**Comment by KiyeonSeo** [comment]
@minihallo-neo 책임님, 위의 List에 있는 펜들 그리다보드 사용가능하도록 BTID 등록 요청 드려욤~

**Comment by minihallo-neo** [comment]
반영했습니다.
