### ISSUE TITLE
페이지 필기 삭제 기능 선택 시 confirm 창 노출 요망

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#192]
![image](https://user-images.githubusercontent.com/52436213/119815018-0ea09700-bf26-11eb-921b-216fad8025c3.png)

text : 현재 페이지의 필기를 모두 삭제하시겠습니까? (yes / no)

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 이 기능은 현재 적용되어 있는것으로 보이니 이슈 클로즈 해도 괜찮을까요?

**Comment by KiyeonSeo** [comment]
2021.07.23 처리 완료 확인 (서기연)
