### ISSUE TITLE
[기획] 페이지 이탈 시 처리

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#200]
[확인필요] 현재 보드에 변경되었으나 저장되지 않은 항목이 있는지 확인 가능한가? 

페이지 이탈 시 Confirm('보드 내용 저장 후 이동하십시오.') 띄운 후 confirm 처리
==> 문구 추후 변경 예정

### 대상 액션
- 웹브라우저 reload / back / forward / URL 이동
- BI 클릭하여 보드 리스트로 이동
- 보드 관련 메뉴 클릭 (생성/불러오기 등)

**Comment by KiyeonSeo** [comment]
@minihallo 
아래 문구 적용 요청 드립니다. 

*이 보드에서 나가시겠습니까? \n보드를 벗어나면 마지막 저장 후 수정된 내용은 저장되지 않습니다.*

**Comment by minihallo-neo** [comment]
적용된 이슈입니다
