### ISSUE TITLE
우측 상단 개인 icon 클릭시 UI 정리

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#201]
![image](https://user-images.githubusercontent.com/52436213/124568732-3289bd80-de80-11eb-81c8-d0a377bd2aac.png)

- 이름 (Nick name) - 만약 없는 경우, 계정(이메일)에서 '@'앞의 정보를 잘라서 보여줌 (네오 스튜디오와 보여주는 형식 통일)
- 계정 (이메일)
- [버튼] 로그아웃
- [링크] 개인정보 처리방침 (링크 추후 보완 예정)
- [링크] 이용약관 (링크 추후 보완 예정)

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 
앗! 약관/처리방침 URL 확정이 안되어서... 놔둔건데욤... ㅜ.ㅜ 
기획 이슈라구욤!!!

**Comment by Minkyum-Kim** [comment]
ㅠㅠ그럼 종료에 두면 안되지 않을까요 ㅠㅠ

**Comment by KiyeonSeo** [comment]
죄송해요 ㅜ.ㅜ 옮겼습니다. 
@Minkyum-Kim

**Comment by KiyeonSeo** [comment]
@minihallo 링크 URL입니다. 
- 개인정보처리방침 : https://www.neostudio.io/nlc_termofuse/
- 이용약관 : https://www.neostudio.io/nlc_termofuse/

**Comment by KiyeonSeo** [comment]
2021.07.30 처리 확인 완료 (서기연)
