### ISSUE TITLE
[상세뷰] 보드리스트에서 이동시 노출되는 서비스소개 레이어 삭제

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#204]
- 발견 일시 : 2021.07.16 PM 1:00
- 위치 : 보드리스트 > 상세뷰 이동 시
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125889704-320fe5c6-3569-4cdf-91b5-c1812b754732.png)
- 항목 및 설명 : 보드리스트 > 상세뷰 이동시 노출되는 서비스소개 레이어 삭제 (해당 컨텐츠 로그인 페이지 좌측에 노출되고 있음)
- 발생 환경 (OS/크롬 버전) :  Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연

**Comment by Minkyum-Kim** [comment]
@neostudioplan 종료 처리할때 이슈 클로즈도 부탁드립니다.
