### ISSUE TITLE
[보드리스트] 보드 복제 시 프로그레스바 / 로딩바  노출 요망

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#205]
- 발견 일시 : 2021.07.16 PM 1:45
- 위치 : 보드리스트
- 화면 : (캡쳐 포함) ![image](https://user-images.githubusercontent.com/52436213/125893141-a2e73a01-2a32-4623-a6be-81d91dfbc026.png)
- 항목 및 설명 : 보드리스트 > 보드선택 >복제 시 프로그레스바 / 로딩바가 노출되지 않은 상태로 보드가 복제가 되어 사용자가 복제가 진행되고 있는지 인지 하지 못함
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 매번
- 등록자 : 서기연

**Comment by minihallo-neo** [comment]
반영했습니다
