### ISSUE TITLE
[보드리스트] 보드 복제 시 복제된 보드명 규칙

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#206]
- 발견 일시 : 2021.07.16 PM 1:50
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125893459-0e13646f-2be0-42e4-b573-ce381d545cf2.png)

- 항목 및 설명 : 보드리스트 > 보드 선택 > 보드 복제 시 복제된 보드명은 "원본 보드명" + "_사본"으로 보드 이름 설정 요망
   예> 20210716_뉴스레터_사본

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연

**Comment by minihallo-neo** [comment]
반영했습니다

**Comment by KiyeonSeo** [comment]
2021.07.22 처리 완료 확인 (서기연)
