### ISSUE TITLE
[보드리스트] 복제시 오류

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#207]
- 발견 일시 : 2021.07.16 PM 2:05
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125894642-d2e80743-2201-4c0a-a64e-a0c6859f580f.png)

- 항목 및 설명 : '20210716_사후레터' 생성 후 'SmartClassKit~'생성, 보드 리스트에서 '20210716_사후레터' 보드 복제하면 썸네일은 '20210716_사후레터' 그대로 보여지지만, 페이지수 카운트는 SmartClassKit~'과 동일하게 나옴
상세뷰로 이동해서 확인 시 '20210716_사후레터'와 동일한 페이지(수)로 구성되어 있음
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 :계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
7.21 테스트 서버에 반영 예정입니다.

**Comment by KiyeonSeo** [comment]
2021.07.21 처리 완료 확인 (서기연)
