### ISSUE TITLE
[상세뷰] 덮어쓰기 시 저장되는 것 처럼 보이나 실제로는 저장안됨

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#208]
- 발견 일시 : 2021.07.16 PM 2:15
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![2021-07-16 (9)](https://user-images.githubusercontent.com/52436213/125895601-dcbec0a7-cb53-4149-aead-47807812f1e0.png)
![image](https://user-images.githubusercontent.com/52436213/125895615-b15d0933-93bc-4f5c-965a-73a265962ca7.png)

- 항목 및 설명 : 필기 추가 후 저장하기 > 저장하기(덮어쓰기) 선택 시 저장되는 것 처럼 보이나(딤드처리 로딩바) 실제 보드 리스트로 이동해서 해당 보드 다시 선택 시 필기가 저장되어 있지 않음
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
정상 동작 확인했습니다!

**Comment by KiyeonSeo** [comment]
2021.07.21 처리 완료 확인 (서기연)
