### ISSUE TITLE
[보드리스트] 로그인 후 보드리스트 상단 이메일 주소 표시 안되는 현상

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#209]
- 발견 일시 : 2021.07.16
- 위치 : 보드리스트
- 화면 : 
![image](https://user-images.githubusercontent.com/75602294/125896995-d8e7e770-de5d-4c0a-9533-e5fe80fff440.png)

- 항목 및 설명 : 보드리스트에 로그인 했을 때 우측 상단 이메일 주소가 나타나지 않는 에러가 발생합니다. 
아이콘을 클릭했을 때 이메일 주소가 다시 표시되었습니다.
- 발생 환경 (OS/크롬 버전) : window10 / 91.0.4472.124
- 발생 빈도 : 가끔
- 등록자 : 김예림

**Comment by KiyeonSeo** [comment]
저도 일시적으로 발견했습니다. 
재현되는 케이스 확인 시 코멘트 추가하겠습니다.

**Comment by Minkyum-Kim** [comment]
이부분은 처리되었으나 아직 안 올라간것 같습니다.

**Comment by Minkyum-Kim** [comment]
아주 짧지만 로딩하는 구간이 있어 circle progress를 넣으려는 중입니다.

**Comment by neostudioplan** [comment]
종료하겠습니다!
