### ISSUE TITLE
[상세뷰] 새 보드 생성 한 경우, '저장하기 (덮어쓰기)' 메뉴 비활성화 처리

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#210]
- 발견 일시 : 2021.07.16 PM 2:50
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125899046-56b78812-038a-413d-b806-53b9c062877f.png)

- 항목 및 설명 : 보드리스트 > + NEW > 새 보드 생성 한 경우, '저장하기(덮어쓰기)'할 대상이 없으므로 해당 경우 메뉴 비활성화 처리 필요
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
보드리스트에서 '새 보드 생성'을 한 경우에는 처음부터 페이지 하나가 생성됩니다. 기존에 그리다보드에 접속했을 때 페이지가 존재하지 않던 것과는 다른 상황입니다.
그리고 저장하기(덮어쓰기) 라고 돼있는 것은 제가 개발중에 구분하려고 임의로 정해둔 문군데 그냥 '저장하기'라고 생각하시면 비활성화 할 필요는 없어 보입니다.

**Comment by KiyeonSeo** [comment]
2021.07.30 정책 변경하여 처리 확인 완료 (서기연)
