### ISSUE TITLE
[펜연결] 비밀번호 입력창, 비밀번호 입력시 "*"처리 필요

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#213]
- 발견 일시 : 2021.07.16 PM 3:10
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
- ![image](https://user-images.githubusercontent.com/52436213/125900757-ff81e346-456f-4245-b000-d927bfa0c153.png)

- 항목 및 설명 : 펜 비밀번호 입력창에 비밀번호 입력시 현재는 입력된 대로 노출됨, 비밀번호 "*"처리 필요
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by Minkyum-Kim** [comment]
저부분은 크롬 기능인데, 비밀번호표시가 불가능 합니다.
