### ISSUE TITLE
[상세뷰] 한글 텍스트 파일 불러오기 안됨

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#214]
- 발견 일시 : 2021.07.16
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/75602294/125900935-c5484a3f-6fe5-4426-ae6c-6d75ac9a38db.png)

- 항목 및 설명 : 보드리스트 새로 만들기/ 상세뷰 불러오기에서 내용에 한글이 포함된 텍스트 파일(.txt)을 선택했을 때 불러오기가 되지 않고 로딩화면만 나옵니다. 
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 항상
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님, 파일명의 한글여부, 파일내용의 한글여부 도 함께 업데이트 해주세요!

**Comment by neostudioplan** [comment]
1.파일명의 한글여부는 관계없이 불러오기가 되었습니다.

2. 파일 내용에 영어 텍스트만 있을 경우 불러오기가 되었는데
한글이 포함되어있을 때 불러오기가 되지 않았습니다

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님, 테스트했던 파일 첨부 요청 드립니다.

**Comment by neostudioplan** [comment]
@KiyeonSeo 

[한글.txt](https://github.com/neostudio-team/GridaBoard2/files/6866184/default.txt)
[영어.txt](https://github.com/neostudio-team/GridaBoard2/files/6866185/default.txt)
[영어, 한글.txt](https://github.com/neostudio-team/GridaBoard2/files/6866188/default.txt)

한글, 영어, 영어에 한글 텍스트를 추가한 샘플 파일 첨부합니다.
특정한 텍스트 파일 문제는 아닌것 같습니다.

**Comment by KiyeonSeo** [comment]
@minihallo-neo @Minkyum-Kim 확인 요청 드립니다.

**Comment by neostudioplan** [comment]
![image](https://user-images.githubusercontent.com/75602294/126729044-6f3896ad-71e3-474e-bed2-ca3f5345a34a.png)

영어 파일은 import 는 되는데 엔터 공백 줄바꿈이 원래 텍스트 파일과 다르게 나옵니다.

**Comment by Minkyum-Kim** [comment]
1. 이 이슈는 조금 복잡한데, 
예를들면 txt->pdf 로 변환을 할 수있는 엔진과, png->pdf로 변환할 수 있는 엔진등이 전부 각각 다릅니다. 
지금 문제가 된건 txt->pdf 엔진인데, 우선 엔진중 한글이 되는 엔진으로 변경하였습니다. 
기본 default 엔진들중 다른 확장자가 유사한 문제가 발생할 수 있습니다.
이 부분은 다른 확장자에 대해서 문제가 없는지 테스트를 해보는 수 밖에 없을것 같습니다.

**Comment by Minkyum-Kim** [comment]
2. 2번 이슈에 대해서는 저 엔터 공백을 저희가 처리하는게 아니라, 타사 라이브러리를 이용하는 것이기 때문에 해결하기가 조금 어렵습니다.

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 일단 이 이슈는 내용에 한글이 포함된 경우도 import가 되는가를 확인하고 클로즈하겠습니다.

**Comment by neostudioplan** [comment]
내일 확인되면 클로즈하겠습니다. 다른 확장자 파일들도 테스트해보겠습니다~

**Comment by neostudioplan** [comment]
텍스트 파일 정상적으로 불러오기되는것으로 확인했습니다.
