### ISSUE TITLE
[보드리스트/상세뷰] 명령창 Enter 처리 가능 여부 검토

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#215]
- 발견 일시 : 2021.07.16 PM 3:10
- 위치 : 전체
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125900645-67d48755-cfe6-4e2c-95d7-915a21250ad8.png)

- 항목 및 설명 : 현재 '보드 저장', '프린트' 등에서 '저장'/'확인'버튼을 마우스로 클릭해야 동작함, "Enter"로 처리가능 여부 검토 필요
 
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
적용했습니다
