### ISSUE TITLE
[보드리스트] 그룹 내 보드 추가 후 그룹 삭제 시 해당 그룹 하위의 보드 카운트 노출되지 않음

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#216]
- 발견 일시 : 2021.07.16 PM 3:40
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125903329-dabbf04c-b9ac-4def-a108-f73dbdc0227d.png)
![image](https://user-images.githubusercontent.com/52436213/125903516-ca5cde8e-ab7f-4f01-9167-a80986debe28.png)

- 항목 및 설명 : 보드리스트에서 Group 생성하여 여러개의 보드 추가한 후, 해당 그룹 삭제 시 왼쪽 리스트에서는 해당 그룹과 하위 보드도 모두 사라진것처럼 보임, 해당 페이지 재 접근 시는 해당 보드가 'Unshelved'에 다시 추가된 걸 알 수 있음

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
그룹 제거 후 그룹안에 있던 보드들은 Unshelved로 이동되는 것은 의도한 바입니다. 
그룹 제거 후 보드들이 바로 업데이트 되지 않는 문제는 수정했습니다.

**Comment by KiyeonSeo** [comment]
2021.07.30 처리 확인 완료 (서기연)
