### ISSUE TITLE
[상세뷰] 저장하기(덮어쓰기) 오류

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#217]
- 발견 일시 : 2021.07.16
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)

![image](https://user-images.githubusercontent.com/75602294/125904646-6c92f2a0-4a2d-4b20-917a-8d9c22f1e328.png)

- 항목 및 설명 : 저장하기(덮어쓰기)를 눌러서 바로 저장이 되어야하는데 다른 이름으로 저장하기처럼 이름을 입력하는 창이 뜹니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 자주
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님, 이 케이스는 "새 보드"생성으로 들어온 것일까요?
그렇다면 '덮어쓰기'가 불가능한 케이스여서 아예 해당 메뉴가 비활성화 되어야 해서...

**Comment by neostudioplan** [comment]
네네 새보드 생성으로 들어왔어요.
그래서 새보드 만들면 나오는 이름 undefined 에 저장되는걸로 생각했나봐요

**Comment by KiyeonSeo** [comment]
@neostudioplan 
오키! 그럼 이건 #210 과 같은 이슈이니... 클로즈 할께요~
