### ISSUE TITLE
[보드리스트] 보드 선택 > 이동 > 파일 이동 > + 그룹 추가하기 '저장'버튼 활성화 안됨

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#219]
- 발견 일시 : 2021.07.16 PM 4:00
- 위치 : 보드리스트 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/125906213-1b5e70ee-70fe-478c-98ef-2da123903782.png)

- 항목 및 설명 : 보드 선택 > 이동 > 파일 이동 > + 그룹 추가하기 '저장'버튼 활성화 안됨

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by Minkyum-Kim** [comment]
현재 그룹 추가하기의 경우 엔터를 쳐야지 생성이 완료됩니다. 이 부분은 사용성 부분에서 고민이 필요할 듯 합니다.

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 엔터로 동작하자면... 다른 입력 항목들도 모두 엔터로 동작을 해야지 않을까요?

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님, 해당 창의 좌측하단 "+ 그륩 추가하기" 가눙 숨김 처리 요청 드립니다.

**Comment by KiyeonSeo** [comment]
2021.07.8 처리 완료 확인 (서기연)
