### ISSUE TITLE
[펜연결] 비밀번호 검증 오류

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#227]
- 발견 일시 : 2021.07.16
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/75602294/125918076-ae427447-bf62-485c-84b1-d23f765917f1.png)

- 항목 및 설명 : 비밀번호가 4자리일때만 연결이 되어야 하는데, 앞 4개 숫자가 맞으면 5자리,6자리를 입력했을 때도 연결되었습니다.
ex) 비밀번호:0000
연결된 비밀번호: 00000, 000011, 00002 ..

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 항상
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by minihallo-neo** [comment]
수정했습니다

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님, 확인후 처리되었으면 클로즈 해주세요.
