### ISSUE TITLE
[펜연결] 펜 연결 끊김 안내 팝업창 오류

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#228]
- 발견 일시 : 2021.07.16
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/75602294/125919267-be400a18-95ba-452f-b1ea-86bfe03b8f5e.png)

- 항목 및 설명 : 펜 연결이 끊어졌을 때 나오는 팝업창이 확인을 눌러도 여러번 다시 뜨는 오류가 발생합니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 항상
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by minihallo-neo** [comment]
정상 동작 확인했습니다
