### ISSUE TITLE
[보드리스트,상세뷰] 새로고침 404 에러

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#229]
- 발견 일시 : 2021.07.19
- 위치 : 보드리스트, 상세뷰
- 화면 : (캡쳐 포함)

![새로고침 팝업](https://user-images.githubusercontent.com/75602294/126087533-d983f887-4536-4ff6-984f-1d66c1e0347e.JPG)

![새로고침 오류](https://user-images.githubusercontent.com/75602294/126087539-04c5dea1-6f47-43ef-aa15-fcbe8e8c2415.JPG)

- 항목 및 설명 : 보드리스트 및 상세뷰 페이지에서 새로고침을 하면 404 에러가 발생합니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 항상
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by KiyeonSeo** [comment]
@neostudioplan 에러 페이지 뜨지 않고 해당 페이지에 머물러 있도록 처리되었습니다. 최종 확인하고 이슈 클로즈 / 종료 처리 해주세욤

**Comment by neostudioplan** [comment]
보드리스트, 상세뷰에서 새로고침 되는거 확인했습니다. 해당 이슈 종료하겠습니다. 감사합니다!
