### ISSUE TITLE
[상세뷰] 메뉴 겹치는 현상

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#230]
- 발견 일시 : 2021.07.19
- 위치 : 상세뷰 
- 화면 : (캡쳐 포함)
![메뉴 겹침](https://user-images.githubusercontent.com/75602294/126092967-403c33ec-efbe-4f36-b773-16a62d8888eb.JPG)

- 항목 및 설명 : 브라우저 가로 크기를 줄였을 때(1128px) 오른쪽 상단 영역에 있던 메뉴가 아래로 내려와 겹치는 현상이 생깁니다. 
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 항상
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by eunsun1** [comment]
@KiyeonSeo 해당 기능은 해상도 대응 영역으로 이번 오픈에서 지원하지 않는 부분입니다. 해당 부분을 지원하려면 반응형 레이아웃 구성이 되야 하므로 오픈 이후 디자인 /개발 일정을 잡아 작업되야 할것 같습니다. 클로즈 해주세요.

**Comment by KiyeonSeo** [comment]
@eunsun1 일단 클로즈 하겠습니다. 보류로 돌려서 나중에 따로 챙기면 되겠습니다. ^^

**Comment by KiyeonSeo** [comment]
#271과 동일한 이슈로 이 이슈는 종료함
