### ISSUE TITLE
[상세뷰] 페이지 회전시 일시적으로 페이지가 일그러짐

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#234]
- 발견 일시 : 2021.07.20 AM 08:50
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
- 항목 및 설명 : 페이지 회전시 일시적으로 페이지가 일그러짐, 개선 가능 여부 검토 필요

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
회전 방식을 바꾸면 불가능한건 아니지만 현재 회전 관련된 로직들을 다 바꾸는 대공사를 해야돼서 사이드 이펙트가 많이 우려됩니다..
