### ISSUE TITLE
[보드리스트] 상세뷰에서 홈으로 이동했을 때 보드리스트 오류

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#236]
- 발견 일시 : 2021.07.20 
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)

(보드리스트 오류)
![보드리스트 오류](https://user-images.githubusercontent.com/75602294/126276871-175f56c1-21c8-47bb-968d-d98f574e90b8.JPG)

(출력되어야 하는 화면)
![보드리스트1](https://user-images.githubusercontent.com/75602294/126277014-e5e7b877-1bb5-4f20-82b6-c0111b6113f3.JPG)

- 항목 및 설명 : 상세뷰에서 왼쪽 상단 그리다보드 홈으로 돌아가기를 눌러서 보드리스트로 돌아갔을 때 저장된 보드, 그룹, 우측 상단 이메일이 뜨지 않는 현상이 발생했습니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 가끔
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by minihallo-neo** [comment]
정상 동작 확인했습니다.

**Comment by KiyeonSeo** [comment]
해당 케이스 재현 했습니다. 
상세뷰에서 2~3시간 이상 두고 있다가 리스트뷰로 오는 경우 발생합니다. 

![image](https://user-images.githubusercontent.com/52436213/126483040-85660a26-77c3-4151-baa1-f5180435c7e0.png)

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo, @neostudioplan 이번에 애플 로그인부분을 만들면서, 계정부분을 일부분 손봤는데, 이 이슈도 같이 해결되었는지 한번 확인 부탁드립니다!

**Comment by neostudioplan** [comment]
@Minkyum-Kim 테스트해보겠습니다!

**Comment by KiyeonSeo** [comment]
2021.07.30 처리 확인 완료 (서기연)
