### ISSUE TITLE
[프린트] 보드 생성 > 필기 추가 > 프린트 시 추가된 필기 출력 안됨

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#238]
- 발견 일시 : 2021.07.21 AM 10:20
- 위치 : 상세뷰 > 인쇄 팝업
- 화면 : (캡쳐 포함) 
![image](https://user-images.githubusercontent.com/52436213/126416670-6833cdab-4b4c-42eb-be0b-ba1b1c496814.png)

- 항목 및 설명 : 프린트 시 추가된 필기 포함 출력 요망
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by KiyeonSeo** [comment]
별도의 옵션으로 스트록까지 출력하는 기능 제공 고려 필요

**Comment by minihallo-neo** [comment]
#196 과 중복 이슈
