### ISSUE TITLE
[보드리스트] 잘못된 업데이트 날짜

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#239]
- 발견 일시 : 2021.07.21 PM 1:00
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126428971-c1bfe107-1646-4c14-ae8a-864fca6c02ad.png)

- 항목 및 설명 : 오늘 생성/수정했는데 날짜가 2021/6/21로 노출됨
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
업데이트 날짜로 변경되는것 확인했습니다.

**Comment by KiyeonSeo** [comment]
@minihallo 오늘 생성한 보드인데... 
보드 하단에 날짜는 6/22로 나옵니다. 
![image](https://user-images.githubusercontent.com/52436213/126591067-ef20c4df-acb9-4b7e-8912-404b32123f68.png)

**Comment by minihallo-neo** [comment]
월이 -1로 계산되어 나오는 문제로 수정했습니다.

**Comment by KiyeonSeo** [comment]
2021.07.22 처리 완료 확인 (서기연)
