### ISSUE TITLE
[상세뷰] 보드 저장시 토스트 팝업 띄우기

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#240]
- 발견 일시 : 2021.07.21
- 위치 : 상세뷰 
- 화면 : (캡쳐 포함)

![상세뷰-저장](https://user-images.githubusercontent.com/75602294/126443750-390da267-eb73-4100-8393-11b6293daceb.JPG)

- 항목 및 설명 : 보드 저장 후에 저장이 잘 되었는지 확인하기가 어렵습니다. 
보드 저장 완료 시 화면 하단에 '저장되었습니다' 토스트 팝업 추가 부탁드립니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : -
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by minihallo-neo** [comment]
개발 완료했습니다
