### ISSUE TITLE
[상세뷰] 프린트 시 '취소 대기 중' 창 닫히지 않음 

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#242]
- 발견 일시 : 2021.07.21 PM 08:50
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126484946-53899908-ebc3-4e2b-877f-6e3aae916229.png)

- 항목 및 설명 : 가져오기 >  보드 생성  > 저장하기(덮어쓰기) - 보드명 지정 > 필기 > 저장하기(덮어쓰기) 했는데. 보드 이름 입력창 노출됨

- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.3
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by KiyeonSeo** [comment]
이 상태에서 보드리스트로 갔다 돌아와서 필기 > 저장하기(덮어쓰기) 시 해당 창 노출되지 않음

**Comment by minihallo-neo** [comment]
제목과 내용의 이슈가 다른데, 두 이슈 모두 해결되었습니다.
