### ISSUE TITLE
[상세뷰] + > 페이지 추가 시 추가되는 페이지 크기 관련

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#244]
- 발견 일시 : 2021.07.21 PM 9:15
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126486777-94c90a31-50c4-4ca3-9c53-4594dc435a46.png)

- 항목 및 설명 : 페이지 추가 시 해당 보드의 마지막 페이지 기준으로 같은 크기의 페이지 추가 가능 여부 검토 필요
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.3
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
페이지 추가는 가상의 페이지 정보(section, owner, book)를 생성하고 그 페이지 정보에 해당하는 기정의된 종이 정보를 바탕으로 페이지를 생성하고 있습니다. 현재는 A4로 생성하고 있는 상태구요. 
마지막 페이지 크기에 따라 그에 맞는 페이지 정보를 생성하려면 크기에 따라 어떤 페이지 정보를 할당할건지를 정의하는데에 어려움이 있습니다.
