### ISSUE TITLE
[상세뷰] 보드 > 내보내기 > 데이터(.GRIDA) 저장 후, + > 가져오기 > 저장한 GRIDA 파일 선택 시 처리

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#246]
- 발견 일시 : 2021.07.21 PM 9:25
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126487693-dc18d4f1-3fc0-47b9-a90c-1d6af339d1b4.png)
![image](https://user-images.githubusercontent.com/52436213/126488615-14104699-24bd-42ea-a4ae-2d420b016a92.png)

- 항목 및 설명 : 보드 > 내보내기 > 이미지(.PDF) 저장 후, + > 가져오기 > 저장한 PDF 파일 선택 시 '이미 등록된 PDF가 존재합니다."라고 노출되나, 데이터(.GRIDA)파일의 경우 다시 불러오면 페이지가 추가됨
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.3
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
pdf와 마찬가지로 한번 등록된 grida 파일은 재등록되지 않도록 수정했습니다.
