### ISSUE TITLE
[상세뷰] 페이지 삭제 후 toast 처리 요망

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#248]
- 발견 일시 : 2021.07.21 PM 9:40
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126489555-c210ba56-f0e6-4d31-b371-f88990c9196a.png)

- 항목 및 설명 : 페이지 삭제 후 하단에 toast 안내 필요 '페이지가 삭제되었습니다."
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.3
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 앗 날짜를 잘못 보고 처리해버렸습니다

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim ㅎㅎㅎ 밤에 적용되면 확인해보겠습니당.

**Comment by neostudioplan** [comment]
확인했습니다!
