### ISSUE TITLE
[상세뷰] 스마트플레이트 > 상단 컨트롤러 중 두께 설정 동작 하지 않음

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#255]
- 발견 일시 : 2021.07.22 AM 12:20
- 위치 : 보드리스트 상세뷰
- 화면 : (캡쳐 포함)
- 항목 및 설명 :  스마트플레이트 > 상단 컨트롤러 중 두께 설정 동작 하지 않음
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.3
- 등록자 : 서기연
- 사용계정 : Google 로그인 (neostudio.dev@gmail.com)

**Comment by minihallo-neo** [comment]
기능 적용했습니다. 7.26에 확인부탁드립니다.

**Comment by neostudioplan** [comment]
확인했습니다~
