### ISSUE TITLE
[스트링] 보드 > 내용지우기 시 팝업 스트링 정렬 이슈

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#256]
발견 일시 : 2021.07.22
위치 : 보드리스트 좌측 메뉴 bar > '내용 지우기'
화면 : (캡쳐 포함)
![페이지삭제_스트링 정렬](https://user-images.githubusercontent.com/61952421/126576965-a9807e0a-5d0d-424b-8987-645cd3e99e1d.png)

항목 및 설명 : 
발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
발생 빈도 : 계속
발생 기기 : desktop
버전 : V2.3
등록자 : 함종덕
사용계정 : Google 로그인 (neo.jd@neolab.net)

**Comment by KiyeonSeo** [comment]
2021.07.22 개선된 스트링으로 업데이트 후 재검토 예정

**Comment by minihallo-neo** [comment]
반영 완료되었습니다
