### ISSUE TITLE
[덮어쓰기] 신규 보드 생성 후 필기 덮어쓰기 시나리오 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#257]
발견 일시 : 2021.07.22
위치 : 신규보드 

항목 및 설명 : 
[재현 경로]
1. 신규 보드 생성
2. 필기
3. 저장하기 > (다른이름으로 저장)
4. 추가 필기
5. 저장하기 > 덮어쓰기

위의 경로대로 덮어쓰기 할 경우 덮어쓰기가 되지 않고 다른이름으로 저장할때처럼 보드의 이름을 변경하는 유도 팝업이 출력됩니다. 

발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
발생 빈도 : 계속
발생 기기 : desktop
버전 : V2.3
등록자 : 함종덕
사용계정 : Google 로그인 (neo.jd@neolab.net)

**Comment by KiyeonSeo** [comment]
기획에서 검토하겠습니다.

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님,  이 이슈 검토 요청 드립니다.

**Comment by neostudioplan** [comment]
![덮어쓰기](https://user-images.githubusercontent.com/75602294/126583069-447e496e-51ad-45a4-8311-2646a96216dc.JPG)

@KiyeonSeo 
테스트해봤는데 해당 오류 발생하는 경우가 있었습니다. 수정부탁드립니다.

**Comment by KiyeonSeo** [comment]
@neostudioplan 어떻게 처리해야할까요? 구체적으로 고민 좀 해주세요.

**Comment by minihallo-neo** [comment]
한번 저장된 문서는 '저장하기' 기능 사용시 dialog가 뜨지 않고 덮어쓰기가 되도록 수정했습니다.

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, 오늘 "개발완료"항목은 내일오전에 테스트서버에 적용됩니다. 
내일 오전 이후에 확인 후 처리되었으면 클로즈 해주세요~

**Comment by neoJD** [comment]
@minihallo diglog가 뜨지 않는 것을 확인하였습니다만, 실제 필기한 내용이 덮어쓰기 되지 않는 이슈를 확인하였습니다.

영상 확인 부탁드리며, 이슈 다시 한번 검토 부탁드립니다. 

https://user-images.githubusercontent.com/61952421/126740832-4d91509f-30c8-4826-827b-4d073a723279.mp4

**Comment by minihallo-neo** [comment]
수정했습니다. 7.30에 반영될 예정입니다.

**Comment by KiyeonSeo** [comment]
@neoJD 확인 후 클로즈 및 우측 프로젝트에서 '개발완료' ==> '종료' 변경 요청 드립니다.

**Comment by neoJD** [comment]
수정확인하였습니다 해당 이슈 종료처리합니다.

**Comment by neoJD** [comment]
@KiyeonSeo 수석님 저한테 프로젝트 변경 권한이 없는것 같습니다! 한 번 확인 부탁드립니다!
