### ISSUE TITLE
[기획 문의][로그인] 동일 이름의 Google/Apple 로그인을 시도했을 경우 처리 방식 문의

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#258]
발견 일시 : 2021.07.22
위치 : 로그인

항목 및 설명 : 예를들어 'neo.jd@neolab.net' 이란 구글계정과 애플계정이 동시에 존재한다고 할 때, 서버에서 1개의 계정으로 인식하여(?) 동일한 데이터를 불러오고 있습니다. 

cf) 구글로그인 -> neo.jd@neolab.net 계정에서 작성한 데이터가 애플 로그인 -> neo.jd@neolab.net 에서도 동일하게 보이고 있음 

해당 내용이 기획된 내용인지 확인 부탁드립니다.

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, Google/Apple 로그인 구분이 아닌 이메일 계정을 기준으로 동일인 여부를 판별하고 있습니다. 
기획된 내용 맞습니다. 

issue close 요청 드려요~

**Comment by neoJD** [comment]
@KiyeonSeo 확인 감사드립니다.
내용 확인 후 이슈 종료처리합니다!
