### ISSUE TITLE
[보드리스트/문의] 같은 이름의 그룹 추가시,  제재 문구  

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#260]
- 발견 일시 : 2021.07.22 
- 위치 : 보드리스트
- 화면 : 
![image](https://user-images.githubusercontent.com/67988805/126579689-ef5a1143-0b88-4aa6-bd03-e2d8494bc06a.png)

- 항목 및 설명 : 기존의 그룹과 같은 이름의 그룹 신규 생성시, 안내 문구가 없어 문의드립니다. 
                         확인 부탁드립니다. 
- 발생 환경 (OS/크롬 버전) : win 10 pro
- 발생 빈도 : 항상
- 발생 기기 : desktop
- 버전 : V2.0.1
- 등록자 : 김한솔
- 사용계정 : hansol@neolab.net

**Comment by KiyeonSeo** [comment]
@Hansol16 현재 중복에 대해 제한하고 있지 않습니다.

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님~ 요건은 이슈 클로즈 요청 드려요~ ^^

**Comment by Hansol16** [comment]
이슈 아니여서 close 하겠습니다~!
