### ISSUE TITLE
[새그룹 생성] 기존 그룹 이름으로 변경 시, 그룹 메뉴만 클릭해도 그룹이 생성되는 현상 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#261]
발견 일시 : 2021.07.22

위치 : 보드리스트- 새그룹 생성

화면 :
*동영상: https://youtu.be/Vq3CIiwYaRw 

항목 및 설명 : 기존의 그룹과 같은 이름으로 변경 후, 그룹 메뉴 클릭 시 그룹 생성되는 현상
[경로]
1. '여름' 그룹 생성
2. '여름+'그룹 생성
3. '여름+' 그룹 이름 변경> '여름' 변경 완료 
4. 생성된 그룹 점 세개 클릭
5.  같은 이름의 그룹  추가적으로 생성 

그룹 삭제 시도 하였으나 반응 없으며, 새로고침시 404 화면이 뜹니다. 
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro

발생 빈도 : 항상

발생 기기 : desktop

버전 : V2.3

등록자 : 김한솔

사용계정 : hansol@neolab.net

**Comment by neostudioplan** [comment]
![image](https://user-images.githubusercontent.com/75602294/126739789-4f59a697-716c-4c09-95a7-02d65f14d34a.png)

해당 이슈 재현 후 기본 그룹 항목이 사라지는 문제도 확인부탁드립니다

**Comment by KiyeonSeo** [comment]
@neostudioplan 예림님, 바로 위에 기입해주신 내용은 별도의 이슈로 생성해주세요.

**Comment by neostudioplan** [comment]
@KiyeonSeo 새로운 이슈로 등록했습니다 #276

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 
#276 이슈의 경우, 이 이슈 발생과 함께 원래 지울 수 없는 그룹이 버그의 영향으로 접근하게 된 이슈인것 같습니다. #276 이슈는 단독 해결은 불가능 합니다

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 
일단 #261번 처리되면 발견되지 않을 이슈라는 거죠? 
이슈 하나에 여러개의 수정요청을 기입하면 이슈 클로즈 판단이 어려워서.. 일단 분리했습니다. 
#261 처리되면 #276도 함께 클로즈 하겠습니다.

**Comment by KiyeonSeo** [comment]
2021.07.29 처리 완료 확인 (서기연)
