### ISSUE TITLE
[404에러] 주소창에서 새로고침할때  발생하는 문제 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#262]
발견 일시 : 2021.07.22

위치 : 주소창

화면 :
*동영상: https://youtu.be/7lN2PzsmMlo

항목 및 설명 : 주소창에서  새로고침시 404 화면이 뜹니다.
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro

발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.0.1
등록자 : 김한솔
사용계정 : hansol@neolab.net

**Comment by neostudioplan** [comment]
#229 와 중복되는 이슈입니다. 일단 클로즈하겠습니다!
