### ISSUE TITLE
[새그룹 생성] 그룹 이름 길게 생성 시,  보드 영역으로 넘어가는 문제   

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#263]
발견 일시 : 2021.07.22

위치 : 보드리스트- 새그룹 생성

화면 : 
![image](https://user-images.githubusercontent.com/67988805/126582665-92ebb37f-f259-468a-b01d-6ac196c396c5.png)

항목 및 설명 : 그룹 이름 길게 생성 시,  보드 영역으로  그룹이름이 넘어가는 문제입니다.
그룹 메뉴 클릭시 반응이 없어 변경 및 삭제가 불가능합니다.
확인 부탁드립니다.   

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : hansol@neolab.net

**Comment by KiyeonSeo** [comment]
@minihallo @Minkyum-Kim 책임님들~ 혹 아래 기준 적용에 문제가 있을까요? 

### 텍스트 입력 정책 

- 보드명
	- 길이 : 20char
	- 입력가능 문자 : 텍스트(국문,영문,일문,중문,숫자,+,_,-), 공백, .
	- 그 외 조건
		> 공백과 .으로 입력값 시작 불가
		> 텍스트(국문,영문,일문,중문,숫자,+,_,-)이 입력된 상태에서만 텍스트 다음에 공백값과 . 입력 가능함
		> 파일로 보드생성 시 상단에 노출할 보드명은 파일명기준 좌측 20글자만 잘라서 노출


- 그룹명
	- 길이 : 15char
	- 입력가능 문자 : 텍스트(국문,영문,일문,중문,숫자,+,_,-), 공백, .
	- 그 외 조건
		> 공백과 .으로 입력값 시작 불가
		> 텍스트(국문,영문,일문,중문,숫자,+,_,-)이 입력된 상태에서만 텍스트 다음에 공백값과 . 입력 가능함

**Comment by Minkyum-Kim** [comment]
조건 추가하도록 하겠습니다

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님, 오늘 '개발 완료'건은 내일 오전에 개발서버에서 확인할 수 있습니다. 
내일 오전에 확인하신 후 클로즈 해주세요~

**Comment by Hansol16** [comment]
수정 확인되어 close처리 하겠습니다.
