### ISSUE TITLE
[상세뷰] 노트위에 필기할 경우 2페이지부터 반영되는 문제

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#265]
발견 일시 : 21.07.22

위치 :상세뷰

화면 : (캡쳐 포함)

![그리다 노트](https://user-images.githubusercontent.com/80810905/126590580-4b611ce4-2bf1-4c17-b456-9a5911adaf83.JPG)

항목 및 설명 :  네오스마트펜 전용노트에서 필기 시 기존 생성되어있는 1페이지 위에는 필기되지않고 2페이지가 새로 생성되며 그 위에 필기가 반영됩니다.

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
보드 생성 시 첫 페이지가 생성되지 않게 했습니다
