### ISSUE TITLE
[단축키] 동작하지 않는 단축키 정리 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#266]
발견 일시 : 21.07.22

위치 : 상세뷰(페이지뷰)

화면 : (캡쳐 포함)

![단축키 미적용](https://user-images.githubusercontent.com/61952421/126593023-6e9d344b-342a-4a3a-9382-4e94ed69f39a.png)

항목 및 설명 :  위의 이미지에서 빨간 박스에 있는 단축키는 동작하지 않고 있습니다. 
(저장하기와 내보내기 단축키가 'S'로 중복 설정되어있습니다.) 

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 함종덕

사용 계정 : 구글로그인 (neo.jd@neolab.net)

**Comment by Minkyum-Kim** [comment]
우선 프린트와 삭제는 기능을 고쳤고, 내보내기 같은 경우는 우선 단축키 뱃지를 제거했습니다. 내보내기의 경우, 단축키가 다시 잡힌다면 추가 작업을 하도록 하겠습니다.

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, 오늘 "개발완료"항목은 내일오전에 테스트서버에 적용됩니다.
내일 오전 이후에 확인 후 처리되었으면 클로즈 해주세요~

**Comment by neoJD** [comment]
위 내용 확인 및 수정 확인하였습니다. (프린트, 삭제 기능 단축키 정상동작 및 내보내기 단축키 제거)
