### ISSUE TITLE
[보드리스트]그룹 선택 후 새 보드 생성- 저장하기 했으나 분류없음으로 저장되는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#267]
발견 일시 : 21.07.22

위치 :보드리스트

화면 : (캡쳐 포함)

![보드1](https://user-images.githubusercontent.com/80810905/126593269-13329795-c3c3-4dca-b48c-290a7d78e80e.JPG)
![보드2](https://user-images.githubusercontent.com/80810905/126593270-397a7f5c-6c3a-4b3e-83a2-c26235dba1d5.JPG)
![보드3](https://user-images.githubusercontent.com/80810905/126593272-ed7bf7a2-f10f-42bf-ac72-bd40b485fd7e.JPG)

항목 및 설명 : 보드리스트에서 그룹 지정 후 새 보드 생성하여 저장했으나 선택한 그룹이 아닌 분류없음 그룹으로 지정됩니다.

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 송은서

**Comment by KiyeonSeo** [comment]
@eunsuh-song  매니저님, 우리는 그룹지정하영 보드 생성하는 기능은 현재 없습니다. 
이슈 닫읍시다!!!
