### ISSUE TITLE
[페이지 뷰/문의] 펜 교차 사용할 때, 펜 설정에 사용하는 펜 색상 반영 문의 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#268]
발견 일시 : 2021.07.22
위치 : 페이지뷰- 펜 설정 

화면 : 
*동영상: https://youtu.be/duEccQ64nOw

항목 및 설명: 

펜 두 개 연결하여
각각 다른 컬러 설정 후,
번갈아 사용하면  펜 설정에 
사용하는 펜의 색상이 반영 되지 않습니다.

마지막에 설정한 펜 컬러로 유지되고 있습니다. 
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : hansol@neolab.net

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님.
각 펜별로 설정값 유지는 8월버전까지는 적용 못하는 이슈 입니다. 
보류로 돌릴께요.

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님,
이 이슈는 우선순위를 제일 나중으로 미룰께요.
