### ISSUE TITLE
[화면조정] 특정 PDF불러오기 후, 페이지 확대 시 페이지 날라가는 현상

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#270]
발견 일시 : 2021.07.22
위치 : 페이지뷰- 화면조정 

화면 :
![image](https://user-images.githubusercontent.com/67988805/126595920-69ed0c5e-0469-4d0d-935d-063e0196f638.png)
항목 및 설명:

특정 PDF( [디지털뉴딜 로드맵.pdf](https://github.com/neostudio-team/GridaBoard2/files/6860235/default.pdf) )불러오기 후, 
페이지 800%에서 더 확대하려 했을 때, 페이지 날라가는 문제가 발생하였습니다.
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상  
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : hansol@neolab.net

**Comment by Minkyum-Kim** [comment]
![image](https://user-images.githubusercontent.com/81273303/127080482-43774591-3754-401b-9a21-74736d2f9f38.png)
해당 이슈는, 컴퓨팅 퍼포먼스 이슈인듯 합니다.

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님, 500%를 초과하여 확대하는 경우가 흔치 않을 것이라, 최대 500%까지만 확대하도록 처리 예정입니다. 

@Minkyum-Kim 책임님, 최대 500%까지만 확대 가능하도록 처리 요청 드립니다.

**Comment by KiyeonSeo** [comment]
2021.07.29 처리 완료 확인 (서기연)
