### ISSUE TITLE
[보드리스트] 보드 복제시 토스트에서 생성된 보드명 표기 방식 변경

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#273]
- 발견 일시 : 2021.07.22 PM 7:30
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/52436213/126625809-5acfaad4-bb18-4a5a-acf3-cad3d7385d0a.png)

- 항목 및 설명 :  보드 복제시 토스트에서 생성된 보드명 표기 방식 (언더바 삭제)
   문구 : [복제된보드명]으로  보드가 복제되었습니다. 
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 발생 기기 : LG gram
- 버전 : V2.2
- 등록자 : 서기연
- 사용계정 : Google 로그인 (kyseo@neolab.net)

**Comment by neostudioplan** [comment]
확인했습니다. 이슈 클로즈하겠습니다.
