### ISSUE TITLE
[보드리스트] 기본 그룹 사라지는 현상

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#276]
- 발견 일시 : 2021.07.23
- 위치 : 보드리스트
- 화면 : (캡쳐 포함)
![image](https://user-images.githubusercontent.com/75602294/126740714-0907af30-30b0-46a3-88e1-13a970b9abee.png)

- 항목 및 설명 : #261 이슈 재현 후 기본 그룹 항목이 사라지는 오류가 발생했습니다. 로그아웃 후 재로그인을 해봐도 기본 그룹이 노출되지 않았습니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by Minkyum-Kim** [comment]
@neostudioplan 우선 DB에서 데이터를 수정해서 다시 기본 그룹을 생성해드렸습니다.

**Comment by KiyeonSeo** [comment]
해당 이슈는 #261번 처리되면 발견되지 않을 이슈이므로 
#261 처리되면 #276도 함께 클로즈 예정

**Comment by neostudioplan** [comment]
@Minkyum-Kim 
감사합니다 !
