### ISSUE TITLE
[상세뷰] 페이지 삭제 시 튜토리얼 노출

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#279]
- 발견 일시 : 2021.07.23
- 위치 : 상세뷰
- 화면 : (캡쳐 포함)
https://www.youtube.com/watch?v=-QCtOJG1NTs&ab_channel=neostudio

- 항목 및 설명 : 로그인 후 새 보드 생성, 상세뷰에서 페이지 삭제를 할 때 팝업창과 함께 계속 튜토리얼이 뜹니다. 드물게 발생하는 오류라서 일단 보류해놓겠습니다. 추후 확인부탁드립니다.
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 :드물게
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by KiyeonSeo** [comment]
@neostudioplan 요거... '그만보기' 혹은 '다음'버튼 눌러서 끝까지 진행했는데도 그래요?

**Comment by neostudioplan** [comment]
@KiyeonSeo 
다음 버튼은 안눌러봤고 그만보기 눌러도 삭제 버튼 누르면 다시 뜨더라구요..
본문에 동영상도 함께 첨부했습니다

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님 확인해주세요~

**Comment by KiyeonSeo** [comment]
2021.07.28 처리 완료 확인 (서기연)
