### ISSUE TITLE
[고객문의]Ncode A4 이용 시 인식범위 밀림 현상

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#280]
테스트 버전 아닌 기존 그리다보드 문의입니다.

발견 일시 : 21.07.26

참조:https://labs.neostudio.io/topic/295/?tab=comments#comment-767

화면 : (캡쳐 포함)

![고객 테스트](https://user-images.githubusercontent.com/80810905/126922586-8afcbafd-2f44-4084-bb10-616223e74d31.jpg)

항목 및 설명 : Ncode A4 50 이용하여 필기할 경우 첨부 이미지와 같이 상단,좌측에서 10mm정도 떨어져 인식된다고 하십니다.
동일하게 테스트해본 결과 2mm정도 밀려남은 있었으나 10mm까지는 재현되지 않았습니다.

발생 빈도 : 계속

등록자 : 송은서

**Comment by KiyeonSeo** [comment]
@eunsuh-song 같은 기기에서 출력하고 진행하신거죠?

**Comment by eunsuh-song** [comment]
@KiyeonSeo Ncode a4 50 제품 https://store.neosmartpen.com/goods/goods_view.php?goodsNo=72 사용중이라고 하셔서 동일한 제품으로 출력 없이 테스트 진행했습니다!

**Comment by KiyeonSeo** [comment]
"출력 없이" 는 출력안하고 NCODE A4 인쇄페이지 순서 등록해서 테스트 하셨다는 건가요???

일단 저도 NCODE A4 인쇄해서 테스트 해볼께요.

**Comment by KiyeonSeo** [comment]
@minihallo-neo 참고하세요~ 책임님.

**Comment by minihallo-neo** [comment]
수정된 이슈입니다
