### ISSUE TITLE
[상세뷰] Ncode A4 인식 범위 밀리는 현상

### ISSUE THREAD

**Issue by neostudioplan** [neostudio-team/GridaBoard2#282]
- 발견 일시 : 2021.07.26
- 위치 : 상세뷰 
- 화면 : (캡쳐 포함)

(상세뷰에서 필기 인식된 화면)
![그리다보드 인식](https://user-images.githubusercontent.com/75602294/126943130-10edcb20-9c65-42c8-9aa0-6eb511cdf279.PNG)

(실제 필기한 A4 용지)
![그리다보드 인식1](https://user-images.githubusercontent.com/75602294/126943493-6ed10629-c256-4632-9f25-b3bfb098018d.jpg)

- 항목 및 설명 : #280 이슈와 동일하게 그리다보드 테스트버전에서 Ncode A4 용지에 인쇄 후 필기했을 때 인식 범위 차이가 생깁니다. 실제 필기한 내용과 차이가 나는 부분들을 상세뷰에 빨간색 펜으로 표시해두었습니다. 
- 발생 환경 (OS/크롬 버전) : Windows 10 / 버전 91.0.4472.124
- 발생 빈도 : 계속
- 등록자 : 김예림
- 사용계정 : Google 로그인 (neostudio.plan@gmail.com)

**Comment by KiyeonSeo** [comment]
재확인 필요!

**Comment by nhw0223** [comment]
20210817 본부회의때 회장님 확인 요청 사항으로 다시 한번 체크 필요 합니다.

**Comment by minihallo-neo** [comment]
ncode a4에 인쇄한 직후에 뜨는 다이얼로그에서 페이지 순서 등록 진행할 때 발생하는 문제였습니다. 해결되어 이번 주중에 테스트 서버에 반영될 예정입니다.
