### ISSUE TITLE
[로그인/문의] 교육용 서비스 소개 컨텐츠 안내문구 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#285]
발견 일시 : 2021.07.27
위치 : 로그인
화면 : 
![서비스 소개 컨텐츠 안내](https://user-images.githubusercontent.com/67988805/127080839-612d1ddf-cdd6-4e3f-b326-5b6a2a25d9ba.PNG)

항목 및 설명:
wireframe에는 '수업 자료를 출력한 디지털페이퍼에 스마트펜으로 기록하여~'

https://gridaboard-v2-test.web.app/ 에는 '그리다보드에서 출력한 종이로 기록하여~'로 

문구가 일치하지 않아 문의드립니다. 확인부탁드립니다. 

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : 구글(hansol@neolab.net)

**Comment by KiyeonSeo** [comment]
@neostudioplan wireframe 현행화 요청 드립니다.

**Comment by neostudioplan** [comment]
@KiyeonSeo 
확인 후 업데이트하겠습니다

**Comment by neostudioplan** [comment]
@Hansol16 
테스트 버전에 있는 스트링으로 와이어프레임 업데이트했습니다.
https://docs.google.com/presentation/d/1v7TACcz8qskLdIagopY5mIrzyKKda8Js6k9wMMqK8vc/edit#slide=id.ge4436ecff8_1_9
(p.23-교육용)
확인해주시고 이슈 종료부탁드립니다. 감사합니다!

**Comment by Hansol16** [comment]
수정 확인하여 #285 close 합니다.
