### ISSUE TITLE
[내보내기] pdf/grida 내보내기 문서 글자수 제한 확인 필요

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#286]
발견 일시 : 2021.07.27
위치 : 상세 페이지뷰
화면 :

https://user-images.githubusercontent.com/61952421/127081190-a7784a3d-a7c5-47ba-9904-5201a4fb8385.mp4

항목 및 설명:

작성한 페이지를 내보내기할 때, 파일명(글자수)가 20바이트를 넘어가면 아무런 메세지 없이 저장이 안되는 현상이 확인되고 있습니다.  위 현상에 대한 별도의 안내 문구 추가 기획 검토 부탁드립니다. 

발생 환경 (OS/크롬 버전) : win 10 pro // 92.0.4515.107
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 함종덕
사용계정 : 구글(neo.jd@neolab.net)

**Comment by KiyeonSeo** [comment]
@minihallo-neo 책임님, #263 보드명 기준으로 적용이 가능할까요?

**Comment by KiyeonSeo** [comment]
글자수가 입력 가능 범위를 넘어서는 경우에 대한 처리 보완 예정
"파일명의 20자까지만 입력가능합니다."
