### ISSUE TITLE
[페이지뷰] dimo(F30) 연결하여 필기 시, 획 빠지는 문제 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#287]
발견 일시 : 2021.07.27
위치 : 페이지뷰 
화면 :
![dimo](https://user-images.githubusercontent.com/67988805/127083332-7d427bde-2fa2-4a94-81ef-7b2e0a704553.PNG)
> 노트 사용

![스마트플레이트](https://user-images.githubusercontent.com/67988805/127083762-4be3ad04-b9a2-4691-9e1e-258b6c919ba5.PNG)
>스마트 플레이트 사용 

dimo(NWP-F30)연결하여 필기 시, 획이 빠지는 문제입니다.

노트 및 스마트 플레이트에 사용했을 때 동일한 현상이 나타났으며,  
네오스튜디오 및 툴 연결하여 확인 시 위의 현상이 나타나지 않습니다. 
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : 구글(hansol@neolab.net)

**Comment by KiyeonSeo** [comment]
@Hansol16 책임님, 
예전에 라미펜 에코모드에서도 동일한 증상이 발견되었습니다. frame rate 관련 이슈가 아닐까..하는데요. 
라미펜 에코모드/일반모드로 한번 더 테스트 요청 드립니다. (라미펜 에코모드는 네오스튜디오 > 펜설정 에서  설정 가능합니다.)

**Comment by Hansol16** [comment]
@KiyeonSeo  수석님, LAMY(NWP-F80)으로 에코모드 ON/OFF 필기 결과 획 빠짐 증상 나타나고 있습니다. 
이미지 첨부하오니 확인 부탁드립니다. 
![eco_on_off](https://user-images.githubusercontent.com/67988805/127098464-f32794f2-f0b8-4706-afd1-d78bc2cdb1e0.PNG)

**Comment by Hansol16** [comment]
@KiyeonSeo 수석님, 사용가능한 펜 테스트 결과 첨부합니다. 
![image (7)](https://user-images.githubusercontent.com/67988805/127107003-6b1aebd8-a8c2-4ac1-9959-e9b11d9bb036.png)
