### ISSUE TITLE
[단축키] 맥북 Air(M1 chipset) 환경에서 단축키 동작하지 않는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#288]
발견 일시 : 2021.07.27
위치 : 상세 페이지뷰
화면 :

항목 및 설명:

맥북 에어(M1 칩셋) 환경에서 컬러변경(1~0), 회전(TAB) 외 모든 단축키 동작하지 않는 이슈가 있습니다.
 

발생 환경 (OS/크롬 버전) : Mac OS Big Sur 11.2.2 // 92.0.4515.107
발생 빈도 : 항상
발생 기기 : Macbook Air 
버전 : V2.3
등록자 : 함종덕
사용계정 : 애플(kariahn1014@gmail.com)

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님, 
맥에서 단축키 동작하도록 처리가 필요합니다.

**Comment by Minkyum-Kim** [comment]
@KiyeonSeo 제가....맥이 없는데........엄.......어떡하죠..?

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 제자리에... 부팅까지는 되는 맥북에어가 한대 있습니다. ㅜ.ㅜ

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, 부서에 보유하고 있는 맥북 (M1 chipset 포함)으로 테스트 진행시 정상 동작 되는데... 
이건 다음마일스톤으로 넘겨서 책임님 보유하고 계신 장비로 확인하겠습니다.

**Comment by Minkyum-Kim** [comment]
원인 찾아서 해결하였습니다
(원인은 한글시 키값이 달라지는 현상입니다)
