### ISSUE TITLE
[휴지통] 보드 선택하지 않은 상태에서 복원 클릭 시 토스트 뜨는 문제 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#289]
발견 일시 : 2021.07.27
위치 : 휴지통
화면 :
*동영상: https://youtu.be/FwXi6bS-O3g

[경로]
1. 휴지통에 보드 있는 상태
2. 보드 선택하지 않고 복원 버튼 클릭

보드 선택하지 않은 상태에서 복원버튼 클릭시
'선택한 보드가 복원 되었습니다.' 토스트 뜨는 문제입니다.

그룹에 복원된 보드는 없습니다.  확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : 구글(hansol@neolab.net)

**Comment by KiyeonSeo** [comment]
@Minkyum-Kim 책임님, 
휴지통에 있는 보드가 체크되면 우측 상단의 '완전 삭제', '복원'메뉴가 노출되도록 처리 요청 드립니다. 
체크되었다가 풀려서 체크된 항목이 하나도 없다면 해당 항목 숨겨주세요.

**Comment by KiyeonSeo** [comment]
2021.07.29 처리 완료 확인 (서기연)
