### ISSUE TITLE
[상세뷰]스마트 플레이트 필기 후 GRIDA 파일로 내보내기-불러오기 했을때 필기 내용이 없음

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#290]
발견 일시 : 21.07.27

위치 :상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/127099110-84abc0b1-f8c4-406d-ae99-9bb0b002be7c.mp4

항목 및 설명 : 스마트플레이트 위에 필기하고 GRIDA 파일 내보내기- 불러오기 하면 필기 내용이 없는 상태로 불러와집니다.  확인부탁드립니다!

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 송은서

**Comment by KiyeonSeo** [comment]
@eunsuh-song 매니저님 해당 그리다파일 첨부되면 첨부 요청 드립니다.

**Comment by eunsuh-song** [comment]
[ㅎㅇㄹ.zip](https://github.com/neostudio-team/GridaBoard2/files/6882928/default.zip)

해당 GRIDA 파일 Zip파일로 첨부하였습니다!

**Comment by KiyeonSeo** [comment]
@minihallo-neo 책임님, 확인 요청 드립니다.

**Comment by minihallo-neo** [comment]
필기 내용은 보이게 하였으나 플레이트에 필기 후 저장시 필기 위치에 문제가 있어서 시간이 필요할 것 같습니다.

**Comment by minihallo-neo** [comment]
해결되었습니다
