### ISSUE TITLE
[그리다보드 컨트롤러] Pointer 터치 후 필기시 페이지 뷰가 변경되는 이슈

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#293]
발견 일시 : 2021.07.27
위치 : 상세 페이지뷰
화면 :

https://user-images.githubusercontent.com/61952421/127116622-f5b5ef07-32dd-41a1-b44e-1c24cc80faa1.mp4

이슈 내용 :  Landscape로 사용하다가 그리다보드 컨트롤러의 Pointer 터치 후 다시 필기하면 Portrait 뷰로 변경(고정)되는 이슈입니다. 

발생 환경 (OS/크롬 버전) : win 10 pro /   92.0.4515.107(
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 함종덕
사용계정 : 애플로그인 (kariahn1014@gmail.com)

**Comment by KiyeonSeo** [comment]
@minihallo-neo 책임님, 확인 요청 드립니다.

**Comment by neoJD** [comment]
@KiyeonSeo 수석님 이 컨트롤러(이미지)입니다.
![IMG_6639](https://user-images.githubusercontent.com/61952421/127271577-53617355-b752-4d33-8090-7e3b6419338a.jpeg)
