### ISSUE TITLE
[펜 연결] 비밀번호 10회 이상일때 에러메시지 뜨지 않는 문제 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#294]
발견 일시 : 2021.07.28
위치 : 암호 걸린 펜 등록> 펜 비밀번호 
화면 : 
![10회 이상인데 초기화 안됨](https://user-images.githubusercontent.com/67988805/127289179-a04d4440-9d2f-40b1-9072-d8c2188d4a09.PNG)

그리다보드 펜 관련 정책에 
비밀번호 오류입력 횟수 10회 이상일 경우
"비밀번호 입력 횟수 초과하여 펜 데이터를 초기화합니다." 에러메시지 뜨지 않는 문제입니다.
- 펜 연결 끊기며 초기화는 확인되었습니다.
확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : 구글(hansol@neolab.net)

**Comment by minihallo-neo** [comment]
개발 완료됐고 10월초 실서버 반영 예정입니다.
