### ISSUE TITLE
[펜 연결] 펜 비밀번호 입력 팝업 창 에러메시지 문제 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#295]
발견 일시 : 2021.07.28
위치 : 펜 연결 > 비밀번호 입력창
화면 :
![PW_4자리 이상](https://user-images.githubusercontent.com/67988805/127289881-49559aae-c0e9-473a-8712-ec9f13c3397d.PNG)

암호 걸린 펜 등록시 비밀번호 입력 창에 대한 문제입니다.

1. 입력없이 확인버튼 누를 때
2. 숫자 4자리이상 입력 후 누를 때

공백과 글자수 체크 관련 에러메시지 뜨지 않습니다.  
확인 부탁드립니다. 

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 김한솔
사용계정 : 구글(hansol@neolab.net)

**Comment by minihallo-neo** [comment]
10월 초에 반영 예정입니다
