### ISSUE TITLE
[요청] 릴리즈 전 약관 URL 처리 관련

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#303]
발견 일시 : 2021.07.29
위치 : 계정정보 
화면 :

![약관처리](https://user-images.githubusercontent.com/61952421/127412012-b841d7f9-0a6d-4b32-a2ab-90249e57c14b.png)

이슈 내용 : 

개인정보처리방침과 이용약관 관련 URL이 아직 특정되지 않은 것으로 확인됩니다. (금일 오전기준) 
서비스 릴리즈 전 해당 내용 처리 후 릴리즈 부탁드립니다. 

발생 환경 (OS/크롬 버전) : win 10 pro /  92.0.4515.107
발생 빈도 : 항상
발생 기기 : desktop
버전 : V2.3
등록자 : 함종덕
사용계정 : 애플 로그인 (kariahn1014@gmail.com)

**Comment by KiyeonSeo** [comment]
@neoJD 책임님, 

#201 여기에서 챙기고 있는 이슈입니다. ^^

**Comment by neoJD** [comment]
@KiyeonSeo 내용 확인하였습니다~~
감사합니다!
