### ISSUE TITLE
[상세뷰]지우개 기능 사용시 획 삐침 증상 나타나는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#305]
발견 일시 : 21.07.30

위치 :상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/127592070-893832d3-03a3-4bdd-9cf3-9bd8779960cc.mp4

![지우개전후1](https://user-images.githubusercontent.com/80810905/127592741-776f410b-8e12-437f-8085-747b8ef5676d.jpg)

항목 및 설명 : 

스마트플레이트 & ncode A4로 필기 - 지우개 클릭해 필기를 지운 후에 위 영상과 같이 획 삐침 증상이 나타납니다. 확인 부탁드립니다!

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
현재 발생하지 않는 이슈입니다
