### ISSUE TITLE
[상세뷰]지우개 선택 후 필기 삭제시 선택하지 않은 획이 같이 삭제되는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#306]
발견 일시 : 21.07.30

위치 :상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/127604781-c3de312b-6c75-42ca-9ea1-b79255f59931.mp4

항목 및 설명 :

지우개 선택 후 펜으로 필기 삭제를 시도하자 근처에 있는 선택하지 않은 획들이 같이 삭제됩니다. 확인 부탁드립니다~

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
7초 경에 지워지는 획 'ㅣㅇ' 이부분이 한 획으로 그린게 아니고 두획으로 그린건데 같이 지워진건가요?? 만약 두획으로 그렸다면 획이 겹쳐진 곳에 지우개를 사용하신걸로 보입니다. 7초 부분만 제외하면 문제있는거 없는거죠?

**Comment by eunsuh-song** [comment]
@minihallo-neo  두 획으로 그린거 맞습니다! 14,15초 부분에 'ㅏ' 지울때 'ㅇ'이 같이 지워지는데 이것도 확인 부탁드립니다!

**Comment by minihallo-neo** [comment]
현재 발생하지 않습니다
