### ISSUE TITLE
보드리스트에서는 필기 내용 확인되나 클릭 후 상세뷰에서는 보이지 않는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#307]
발견 일시 : 21.08.02

위치 :보드리스트/상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/127824944-da950514-c6db-41c9-b2c6-7e201e72bb1f.mp4

항목 및 설명 :

보드리스트에서는 보드 상에 필기가 있는 것으로 확인이 되지만 클릭해서 들어갔을때 아무런 내용도 확인되지 않는 이슈가 재현됩니다. 스마트 플레이트를 사용해 필기했습니다.

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 잦음

등록자 : 송은서

**Comment by minihallo-neo** [comment]
수정된 이슈입니다
