### ISSUE TITLE
[상세뷰]저장한 보드 열었을때 '해당 보드에 이미 등록된 PDF 파일입니다'문구와 함께 페이지 사라짐

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#309]
발견 일시 : 21.08.09

위치 : 상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/128664255-33ef6107-e84a-4af4-bcb4-a1556b0ad1c4.mp4

항목 및 설명 :

상세뷰에서 파일 불러오기한 후 필기(마우스,펜)-저장한 후 보드리스트에서 다시 클릭했을때 '해당 보드에 이미 등록된 PDF 파일입니다.' 문구와 함께 페이지,필기 사라짐. 확인 부탁드립니다~

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.107

발생 빈도 : 잦음

등록자 : 송은서

**Comment by minihallo-neo** [comment]
수정된 이슈입니다
