### ISSUE TITLE
[상세뷰]보드를 클릭할때마다 직전에 열었던 보드의 페이지가 나타났다가 돌아오는 증상

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#310]
발견 일시 : 21.08.10

위치 : 상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/128831317-26192acd-d516-45fd-9b27-1fdcf06ba190.mp4

항목 및 설명 :

보드를 클릭해서 상세뷰로 진입 시 직전에 열었던 보드의 페이지가 켜졌다가 사라집니다.확인부탁드립니다

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.131

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
수정되었습니다
