### ISSUE TITLE
[보드리스트/상세뷰]에서 새로고침 시 Page Not Found 에러발생

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#315]
발견 일시 : 21.08.26

위치 : 보드리스트/상세뷰

화면 : (캡쳐 포함)

https://user-images.githubusercontent.com/80810905/130899399-f4a04fa4-e0ef-470e-9bb8-e54ee38cea92.mp4

항목 및 설명 :

그리다보드 접속 후 새로고침을 하면 page not found 에러가 발생합니다. 확인부탁드립니다!

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 92.0.4515.159

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
수정 완료했습니다
