### ISSUE TITLE
[프린트] 일반 복사 용지에 인쇄 선택 시 좌,우 여백 차이 문의

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#317]
- 발견 일시 : 2021.09.03
- 화면 : 
![이미지 2](https://user-images.githubusercontent.com/68038112/131935748-9f289146-52f6-42aa-b351-98bcd99b3200.png)

- 항목 및 설명 : 프린트 > 일반 복사 용지에 인쇄 > 인쇄 미리보기 화면에서 우측 부분에 여백이 발생하고 있습니다. 
정상동작인지 확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by minihallo-neo** [comment]
설정 더보기 - 배율에서 인쇄 가능 영역에 맞춤으로 바꾸시면 됩니다. 현재는 기본값으로 돼있어서 그런거 같습니다
