### ISSUE TITLE
[프린트] Ncode 농도 연하게, 보통 선택해도 진하게로 출력되는 문제

### ISSUE THREAD

**Issue by songkyungha** [neostudio-team/GridaBoard2#318]
- 발견 일시 : 2021.09.03
- 화면 : 
- 항목 및 설명 : 프린트 > 고급 설정 > 용지 크기와 농도 > Ncode 농도를 연하게, 보통 선택 시 진하게로 출력되는 문제입니다.
확인 부탁드립니다. 
- 발생 빈도 : 항상
- 앱버전 : 그리다보드 2.0
- 등록자 : 송경하

**Comment by minihallo-neo** [comment]
수정되어 10월 초 반영 예정입니다
