### ISSUE TITLE
[상세뷰]플레이트 필기 후 내보내기 했을때 필기 위치가 이동되는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#319]
발견 일시 : 21.09.08

위치 : 상세뷰

화면 : (캡쳐 포함)
![필기한내용](https://user-images.githubusercontent.com/80810905/132431905-fd3fba06-3e7f-4f57-bbd4-48fe5667a218.JPG)
![내보내기한PDF파일](https://user-images.githubusercontent.com/80810905/132431918-94509fc7-6851-41fa-9681-2209b06b2098.JPG)

항목 및 설명 : 플레이트에 필기 후 PDF로 내보내기 후 내보내기 한 PDF 파일을 열었을때 기존 필기한 위치와 다르게 나타납니다.
(무조건 왼쪽 위로 이동) GRIDA 파일로 저장하기 또한 증상 같습니다.

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 93.0.4577.63

발생 빈도 : 계속

등록자 : 송은서

**Comment by eunsuh-song** [comment]
본 이슈와 더불어 해당 이슈또한 같이 재현됩니다. 확인 부탁드리겠습니다.   
https://github.com/neostudio-team/GridaBoard2/issues/311

**Comment by minihallo-neo** [comment]
수정된 이슈입니다
