### ISSUE TITLE
[상세뷰]화면 확대/축소 버튼 클릭 시 반응없는 이슈

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#321]
발견 일시 : 21.09.23

위치 : 상세뷰

화면 : (캡쳐 포함)

![확대안됨](https://user-images.githubusercontent.com/80810905/134466818-f270ffa8-c984-4869-85e4-ee1e4e95fdc0.JPG)
![확대안됨2](https://user-images.githubusercontent.com/80810905/134466823-13f3c82b-7f53-470f-b063-244c88ae73a2.JPG)

항목 및 설명 : 필기 후 페이지 확대/축소 버튼 클릭해도 아무런 반응이 없습니다. 확인부탁드립니다!

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 94.0.4606.54

발생 빈도 : 계속

등록자 : 송은서

**Comment by minihallo-neo** [comment]
수정해서 반영했습니다
