### ISSUE TITLE
[긴급][고객사 VOC] F30 (MT2523S 칩셋) 펜 연결 시 펜 굵기 반영되지 않는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#322]
발견 일시 : 2021.09.27
위치 : 펜 연결 
화면 :

그리다보드에 NWP-F30 (MT2523S 칩셋) 펜을 연결하면 펜 굵기가 반영되지 않는 이슈입니다.
추가로 긴 한 획을 그릴 시 중간중간 획이 빠지는 이슈도 확인되었습니다. 

이슈 검토 부탁드립니다. (확인을 위한 펜 시료가 필요하시면 말씀부탁드립니다.)

발생 환경 (OS/크롬 버전) : win 10 pro
발생 빈도 : 항상
발생 기기 : desktop
버전 : 
등록자 : 함종덕

**Comment by minihallo-neo** [comment]
펜 굵기가 반영되지 않거나 중간중간 획이 빠지는 건 샘플 펜 모델인 F30K의 필압이 다른 펜들에 비해 낮게 들어오는 것이 원인입니다. 해당 모델일 경우 필압을 임의로 높여서 렌더링 되도록 처리했습니다.
