### ISSUE TITLE
[페이지뷰] 페이지 회전 후 삭제 시, 페이지 썸네일 이미지 실시간 업데이트 되지 않는 현상 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#371]
발견 일시 : 2022.02.04
위치 : 페이지 뷰 > 썸네일

설명 :
[경로]
1. PDF 파일로 페이지 추가 
2. 회전
3. 해당 페이지 삭제 

[설명]
 경로대로 진행 시 좌측 페이지 리스트에는 이전 페이지의 썸네일이 나타나고 있습니다.
 삭제 직후 해당 페이지가 페이지 뷰에 남아있으며 ,  다른 페이지 이동 후에는 삭제됨을 확인하였습니다.

영상: https://youtu.be/iSLarYnH450

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인(hansol@neolab.net)

**Comment by Minkyum-Kim** [comment]
해당 버그 수정후 업로드 예정입니다.

**Comment by Minkyum-Kim** [comment]
업로드 하였습니다.

**Comment by Hansol16** [comment]
수정 확인되어 이슈 close합니다.
