### ISSUE TITLE
[도움말] 스마트 제스처 메뉴얼 실행되지 않는 이슈

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#372]
발견 일시 : 2022.02.04
위치 : 페이지 뷰 > 도움말

설명 :

스마트 제스처 메뉴얼 선택했을 때, 
메뉴얼이 나타나지 않는 현상으로 확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 이 부분은 제스처 메뉴얼 파일이 나오는대로 업데이트 할 예정입니다.

**Comment by MHCHOI3** [comment]
#377 업데이트 완료하였습니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
테스트 서버에서 제스처 메뉴얼 실행 확인되어 close합니다
