### ISSUE TITLE
[Drag & Drop] 이름없는 파일 drag & drop시 반응 없는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#379]
발견 일시 : 2022.02.07
위치 : 도메인 접근
(https://gridaboard-v2-test.web.app/app)
설명 :

이름 없는 문서 ex) .pptx 파일 drag & drop 시 무한로딩 반복되는 이슈입니다. 

월요회의 대표님 지적사항으로 기획적 논의 및 동작 수정이 필요할 것으로 보입니다. 

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Seo-Wonho** [comment]
안녕하세요. 확장자가 pdf 이거나 grida인 파일을 제외한 모든 파일 중 파일명이 " . " (마침표)로 시작할 경우, drag&drop 혹은 파일 불러오기 시 컨버팅 과정 중에 이슈가 발생하는 것을 확인하였습니다.  
![image](https://user-images.githubusercontent.com/94896134/152898419-82869200-76d5-4204-b1b6-62235289f62e.png)

이슈 확인 후, 해당 동작 수행 시 동작을 막고 경고창을 띄우게 하였으며, 위의 경고문구와 같은 외국어가 필요할 것으로 보입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by neoJD** [comment]
이슈 수정 확인하였습니다. (.csv / .hwp / .xlxs 파일을 불러오기 또는 드래그&드롭했을 때 경고 문구 출력)
종료처리 하도록 하겠습니다.
