### ISSUE TITLE
[Gesture] 좌측 영역 (페이지 회전) 터치로 페이지 회전 2번 동작시 윗 페이지로 이동되는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#380]
발견 일시 : 2022.02.07
위치 : 페이지뷰 

설명 :

왼쪽 영역 터치로 페이지 회전 반복 동작시 해당 페이지에서 계속 회전이 되지않고, 1회 회전동작 후 윗 페이지로 이동하는 이슈입니다. 

[재현경로]
1. 파일 불러오기 (3페이지 이상)
2. 펜 연결 후 마지막 페이지에서 회전 (gesture) 반복 동작 
3. 페이지 회전 여부 확인 

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Minkyum-Kim** [comment]
회전을 이용하게 될 경우, 기획 의도상 플레이트를 같이 회전하도록 되어 있습니다. 현실에서 플레이트를 같이 돌린 이후 다시 재스쳐를 하게 될 경우 정상 동작합니다.

이 부분은 윤수아책임님(@Osupernov ) 과 같이 논의해봐야 할것 같습니다.

**Comment by MHCHOI3** [comment]
추가내용입니다.
회전을 한 뒤 '심볼의 위치 확인' 토스트 메세지와 함께 보여지는 심볼을 현실 플레이트에서의 심볼과 맞춰 사용하셔야 합니다.

**Comment by neoJD** [comment]
@Osupernov 기획적으로 현실 플레이트를 돌려사용하는 것으로 되어있다면, 해당 이슈 종료처리하도록 하겠습니다.
더블 체크 부탁드립니다.

**Comment by neoJD** [comment]
+ 심볼을 확인 후 사용하도록 기획된 내용으로.. 
이슈 종료 처리하겠습니다.
