### ISSUE TITLE
[보드 생성 에러] 파일불러오기 시 무한 로딩 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#383]
날짜 : 22.02.07
위치 : 그리다보드 홈 > new > 파일불러오기로 파일 생성

설명 :

특정 파일(첨부) 로 파일 열기 시 열리지 않고, 무한 로딩에 빠지는 이슈입니다. 
해당 파일 첨부드리니 이슈 확인 부탁드립니다. 

이미지 : 

![파일불러오기실패](https://user-images.githubusercontent.com/61952421/152730269-cc2757db-459a-4e62-9647-3bfaea503340.png)

첨부 : 
[NWP-F53 TP 신뢰성 시험보고서 211112.xlsx](https://github.com/neostudio-team/GridaBoard2/files/8012659/NWP-F53.TP.211112.xlsx)

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕

**Comment by Minkyum-Kim** [comment]
![image](https://user-images.githubusercontent.com/81273303/152730911-f89f2bfc-2c21-4ed4-bea5-11c3ff7a3d97.png)
해당파일은 제 노트북에서는 정상적으로 열리는듯 합니다..이 이슈는 좀더 찾아보겠습니다.

**Comment by Minkyum-Kim** [comment]
무한 로딩에 대하여 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
해당 파일로 무한로딩에 대해 수정 확인하였습니다.
- [NWP-F53 TP 신뢰성 시험보고서 211112.xlsx]
