### ISSUE TITLE
[Gesture][기획] 필기 지우기 gesture 동작 기획 확인 요청 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#386]
발견 일시 : 2022.02.07
위치 : 페이지 뷰 

설명 :

필기 지우기 gesture 동작이 한 쪽 방향(좌상단에서 우하단) gesture만 동작하고 반대 방향은 동작하지 않고 있습니다. 
기획 내용이 변경된 것인지 더블체크 부탁드립니다. 
![필기지우기](https://user-images.githubusercontent.com/61952421/152737873-e94dcfb6-8fa1-4275-98b3-4e38ad99513f.png)

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인(neo.jd@neolab.net)

**Comment by MHCHOI3** [comment]
안녕하세요. 필기 지우기 gesture는 좌상단에서 우하단으로 긋기, 우상단에서 좌하단으로  긋기 (2가지 모두) 충족되어야 동작하는 제스처입니다. 이때, 순서는 그어야 하는 순서는 상관이 없습니다.

**Comment by MHCHOI3** [comment]
안녕하세요. 필기 지우기 제스처는 1. 좌상단에서 우하단으로 긋기, 2. 우상단에서 좌하단으로 긋기 (2가지 모두)를 충족해야 동작하는 제스처 입니다. 이때, 1/2 대각선을 긋는 순서는 상관 없습니다.

**Comment by neoJD** [comment]
이슈를 등록할떄는 "1. 좌상단에서 우하단으로 긋기"만 해도 필기 내용이 지워졌는데, 새로 로그인 후 진행해보니 재현되지 않습니다. 해당 내용 조금 더 확인해보고 내용 업데이트 드리도록 하겠습니다.

**Comment by MHCHOI3** [comment]
* 해당 이슈 확인 후 테스트 중 발견하였습니다.
설명: 페이지를 생성한 후 대각선(1 or 2) 하나를 긋고, 그리다보드 홈으로 이동 후 다시 페이지를 생성하여 다른 대각선을 그을시 필기 지우기가 동작하는 것을 확인했습니다. (더블탭도 마찬가지)

- 라이프 사이클을 생각하지 않고, 초기화를 제대로 하지 못해 일어난 이슈로 보입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by MHCHOI3** [comment]
추가 내용입니다.
작업페이지에서 대각선(1 or 2) 하나를 동작하고, 다른 페이지로 이동하여 나머지 대각선을 동작했을 때도 동일한 증상(gesture가 동작해버림.)이 있어 수정하고 업데이트할 예정입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
이슈 수정 확인되어 close 합니다
