### ISSUE TITLE
[제스처/문의] + 심볼 실행 시, 페이지 레이아웃 landscape로 나타나는 현상

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#387]
발견 일시 : 2022.02.07
위치 : plate> +심볼

설명 :
플레이트의 +심볼 제스처 실행 시 
기존 레이아웃의 형태(portrait) 페이지 추가가  아닌 

landscape(가로)로 페이지 추가되는 현상으로 확인 부탁드립니다.

영상: https://youtu.be/vfBht69vY4Q

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 해당 심볼 터치로 인한 페이지 생성은 기획상 landsacpe로 생성하게 되었습니다.

**Comment by Hansol16** [comment]
#close
