### ISSUE TITLE
[제스처/기획] 더 이상 이동할 페이지 없을 때 토스트 팝업 위치 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#389]
발견 일시 : 2022.02.07
위치 : 페이지> 페이지 이동 

설명 :
더 이상 이동할 페이지 없는 상태에서 
페이지 상단 펜 제스처 영역 더블 탭할 경우 생기는 현상입니다.
기획서엔 토스트 팝업이 상단으로 표시되어 확인 부탁드립니다.
  

사진: 
![image](https://user-images.githubusercontent.com/67988805/152750766-b937afb1-9ef6-420e-8f75-e9eb2af02e7a.png)

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 토스트 팝업은 기획서에 나와있는 포지션이 아닌 현재 포지션에서 표시되는걸로 결정되었습니다.
