### ISSUE TITLE
[hover] 노트 드로잉 시, hover 위치가 일치하지 않는 현상 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#393]
발견 일시 : 2022.02.08
위치 : 페이지 뷰

설명 :
노트에 필기 시 hover 위치가 필기 하는 위치가 아닌 
다른 방향에서 나타나는 현상으로 확인 부탁드립니다.

영상: https://youtu.be/BlwHtzGt2pY

사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))
발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99 
발생 빈도 : 항상
발생 기기 : Laptop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by MHCHOI3** [comment]
수정완료하였습니다. (test 서버 deploy는 익일 예정입니다.)

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by MHCHOI3** [comment]
추가내용입니다.

1. 플레이트로 페이지 생성 
2. 플레이트에서 사용 
3. 바로 펜을 노트에서 사용(노트로 생성된 페이지로 이동)
1->2->3 진행시 hover point가 맞지 않는 문제를 확인하였습니다.

수정 후 업데이트 하겠습니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
플레이트 페이지 생성> 플레이트사용> 펜으로 노트 사용 시 
hover point 수정 확인 되어 close합니다.
