### ISSUE TITLE
[상세뷰]테스트 페이지 스마트 플레이트 필기 시 세로로 써지는 현상

### ISSUE THREAD

**Issue by eunsuh-song** [neostudio-team/GridaBoard2#395]
발견 일시 : 22.02.08

위치 :상세뷰

화면 : (캡쳐 포함)

![플레이트필기](https://user-images.githubusercontent.com/80810905/152927811-abc39443-0e45-404e-88fd-7e520253bed1.JPG)

항목 및 설명 :

테스트 페이지에서 스마트플레이트&페이퍼 플레이트로 가로 필기 시 화면상 세로로 써집니다

발생 환경 (OS/크롬 버전) :윈도우 10 / 크롬 버전 97.0.4692.99

발생 빈도 : 계속

등록자 : 송은서

**Comment by MHCHOI3** [comment]
안녕하세요. 혹시 페이지를 버튼으로 생성하셨나요? 버튼으로 생성된 페이지는 portrait(세로)으로 플레이트 또한 세로로 놓으시고 사용하도록 기획되어있습니다.

현재 스마트플레이트를 처음 터치하셨을때 보여지는 (+) 심볼과 현실에서의 스마트플레이트의 심볼위치를 동일하게 맞춘상태에서 필기를 하도록 기획/개발 되어있습니다. 이전 버전의 플레이트(1, 2)의 경우에는 터치를 하여도 심볼이 보여지지 않으므로 상단의 PUI 위치를 통해 페이지의 상태를 짐작하여 사용해야 될 것으로 보입니다. 이 부분은 윤수아책임(@Osupernov )님 과 같이 논의해봐야 할것 같습니다.
