### ISSUE TITLE
[스크롤] 페이지 넓이 맞춤 후 화면 아래쪽에 필기 시 스크롤이 고정되어 상단으로 올라가지 않는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#396]
발견 일시 : 2022.02.08
위치 : 페이지 뷰

설명 :

페이지뷰에서 '페이지 넓이 맞춤' 으로 한 뒤 화면 아래쪽에 스트로크가 들어갈 시 스크롤이 고정되어 상단으로 스크롤 이동을 할 수 없는  이슈입니다.

[재현 경로]
1. 임의의 pdf 파일 불러오기
2. 페이지 넓이 맞춤
3. 보여지는 화면 아래쪽에 필기 시도
4. 스크롤 확인

발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인(neo.jd@neolab.net)

**Comment by Minkyum-Kim** [comment]
익일 적용될 예정입니다

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
이슈 수정 확인되어 close 합니다
