### ISSUE TITLE
[내보내기] 부기보드에 필기 후 내보내기 시 필기가 좌측으로 90도 회전되어 저장되는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#397]
발견 일시 : 2022.02.09
위치 : 페이지 뷰

설명 :

PDF로 보드 생성 후 부기보드에 필기 -> 내보내기 시 필기가 좌측으로 90도 회전되어 저장되는 이슈입니다. 
이미지 파일과 내보내기로 생성된 PDF파일 첨부드립니다.

이미지 : 
![이미지 1](https://user-images.githubusercontent.com/61952421/153098113-215ae31f-5d35-4691-bde0-1d16f8e7a991.png)

내보내기되어진 파일 :
[PDF로내보내기테스트.pdf](https://github.com/neostudio-team/GridaBoard2/files/8028412/PDF.pdf)

발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Minkyum-Kim** [comment]
#421 로 이슈 처리 되었습니다

**Comment by neoJD** [comment]
수정 확인 후 이슈 종료처리합니다.
