### ISSUE TITLE
[보드이름][기획] 동일한 보드이름으로 저장이 되는 정책 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#398]
날짜 : 22.02.09
위치 : 페이지 뷰

설명 :

현재 중복된 보드이름으로 저장이 가능하도록 구현되어있는데, 이럴 경우 보드 수정후 덮어쓰기 할 경우 어떤 보드에 덮어씌워지는지 정책적으로 논의가 필요할 것 같습니다. 

테스트 결과, 수정 후 덮어쓰기 시 저장이 되지 않고 있습니다. 

동일한 보드이름으로 저장이 불가능하도록 정책적으로 막는 방법 등의 조치가 필요할 것 같습니다. 검토 부탁드립니다.

이슈 영상 : 

https://drive.google.com/file/d/147-SYZmPNyb3zYdCmaZkoLRv6PkA-ZC3/view?usp=sharing

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Osupernov** [comment]
네, 해당 이슈 확인 및 검토 후 답변 드리겠습니다.

**Comment by Minkyum-Kim** [comment]
우선 동일 이름으로 저장되는 것은 작년 8월 온라인 서비스 기획 당시 기획된 부분입니다. 
수정 후 덮어쓰기가 안되는 부분은 버그로 보입니다. 해당 버그 먼저 수정하도록 하겠습니다. 

이외의 기획적인 부분에 대해서는 좀더 토의가 필요할 것으로 보입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
보드명 동일한 경우 수정 후 덮어쓰기 부분 저장되지 않음 
->테스트 서버에서 이슈 수정 확인되었습니다.

**Comment by neoJD** [comment]
동일한 이름으로 보드 저장 가능 -> 기획 확인

저장안되는 이슈 수정 확인 완료 -> 종료 처리합니다.
