### ISSUE TITLE
[.GRIDA 불러오기] 그리다파일 불러오기 > 수정 > 덮어쓰기 시 저장되지 않는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#399]
날짜 : 22.02.09
위치 : 페이지 뷰

설명 :

.grida 파일로 저장 > 불러오기 > 해당 보드에서 수정 후 덮어쓰기로 저장할 경우 그리다보드 홈에 보드 생성되지(저장되지) 않는 이슈입니다. 

[재현 경로]
1. 그리다보드 홈
2. new -> 파일로 불러오기
3. 임의의 .grida 파일 선택
4. 펜 연결 후 임의의 내용 필기
5. 덮어쓰기 저장 -> 그리다보드 홈으로 이동
6. 저장 여부 확인

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Minkyum-Kim** [comment]
수정완료하였고, 익일 적용 예정입니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
수정 확인되어 close 합니다.
