### ISSUE TITLE
[프린트]인쇄 취소할 경우 인쇄 페이지 순서 등록창 뜨는 현상 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#401]
발견 일시 : 2022.02.09
위치 : 페이지 뷰> 프린트 

설명 :

[경로]
1. 네오스마트펜용 인쇄 옵션: Ncode A4 용지에 인쇄 , 재인쇄용 PDF 파일 다운로드  설정값 선택

2. 인쇄 준비중 프로그레싱 바 완료 

3. 인쇄 취소 선택

[설명]
위의 경로대로 진행 시, 프린트 취소했음에도
인쇄 페이지 순서 등록 창이 뜨는 현상입니다.
프로그레싱 바 완료 전에 취소 시 , 인쇄 페이지 순서 등록창이 생성되지 않아 확인 부탁드립니다.

영상: https://youtu.be/2J8RCZttXv8

사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))
발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Laptop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by Minkyum-Kim** [comment]
현재 인쇄창이 꺼졌을때, Ncode A4 용지에 인쇄 옵션을 선택했으면 순서 등록창이 나오도록 설정되어있습니다.

인쇄창이 꺼지는 순간은 파악이 가능하나, 이게 인쇄를 진행해서 꺼진것인지, 취소해서 꺼진것인지는 코드상 파악 할 수가 없습니다.

프로그레싱 바 완료 전에는 반드시 취소이기때문에 안띄우지만, 인쇄창이 켜진 순간부터는 알 수 없기 때문에 띄우는 상황입니다. 

감사합니다

**Comment by Hansol16** [comment]
#close
