### ISSUE TITLE
[파일로 보드 생성] 파일명에 특수문자 (e.g. "!!@#.pptx") 가 포함된 파일을 열 경우 동작 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#409]
날짜 : 22.02.10
설명 :

파일명에 특수문자가 포함된 파일로 보드를 생성할 경우 무한로딩 상태에 빠지며 파일이 열리지 않는 이슈가 있습니다.
기획/동작 확인 더블체크 요청드리며, 이슈 검토 부탁드립니다. 

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 현재 MacOS, Window에서 '!!@#.pdf' / '!!@#.pptx' 로 테스트 해 본 결과  정상적으로 열리는 듯합니다. 
pptx의 경우 convert 하는 시간이 좀 오래 걸려 대기시간이 긴 느낌은 받았습니다.  

그 외의 특이점이 있다면 특수문자가 있는 파일을 열었을 때, window의 경우는 해당 파일의 이름이 제대로 노출되고, mac에서는 파일 이름이 undefined로 표시되는 점이 있었습니다. 해당 부분은 좀 더 확인해보겠습니다.

추가로 기획적으로 특수문자가 포함된 파일을 열 경우의 동작을 검토해주시면 감사하겠습니다. @Osupernov

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
파일명 '!!@#.pptx'로 파일 불러오기 실행할 수 없음 확인하여 close합니다.
-보드> 파일로 보드 생성(pdf 등)

추가적으로 특수문자 포함된 파일( ex. 'test!!@#.pptx')은 열리고 있습니다.
