### ISSUE TITLE
[동작 문의] PDF파일로 보드 생성 > 필기 > 인쇄할 경우 필기한 내용 사라지는 동작 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#410]
PDF파일로 보드 생성한 후 부기보드에 임의의 내용 필기한 상태에서 인쇄를 할 경우 
기록해뒀던 필기 내용이 모두 사라지는 동작은 의도된 동작인지 확인 부탁드립니다.

**Comment by Minkyum-Kim** [comment]
넵. 기획 의도인것으로 알고있습니다

**Comment by neoJD** [comment]
기획 확인 / 종료처리하겠습니다.
