### ISSUE TITLE
[페이지 비율] 회전 후 플레이트> 노트 사용 시 페이지 비율 맞지 않는 현상  

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#413]
발견 일시 : 2022.02.10
위치 : 페이지 뷰

[경로]
1. 노트로 빈 페이지 생성(portrait)
2. 해당 페이지에 플레이트로 필기(portrait)
3. 해당 페이지 회전
4. 해당 페이지 플레이트로 필기(landscape)
5. 1번에 사용했던 노트 페이지에 필기 (portrait) 

[사진]
![image](https://user-images.githubusercontent.com/67988805/153359900-6cfda3c9-4265-4ba2-92a1-0520dec81cd4.png)

위의 경로대로 진행 시
노트 페이지 portrait으로 나오는 대신 실제 필기 할 수 있는 영역은
landscape인 현상으로 페이지 비율이 맞지 않아 확인 부탁드립니다. 

영상: https://youtu.be/ZU54dvYlj7M

발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Laptop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by Hansol16** [comment]
![0224](https://user-images.githubusercontent.com/67988805/155439535-fb7bb248-c58a-4b00-a2b4-f6bc65f81386.PNG)
책임님, 해당 이슈 수정되지 않아 확인 부탁드립니다.

**Comment by Minkyum-Kim** [comment]
다시 확인해 보겠습니다

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
해당 이슈 수정 확인했습니다
