### ISSUE TITLE
[펜 비밀번호] 올바르지 않은 비밀번호 2회 입력 시 1회 카운트하는 현상 

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#414]
발견 일시 : 2022.02.10
위치 :  펜 연결하기 

설명:

1. 비밀번호 설정된 펜 
2. 펜 연결하기 실행
3. 올바르지 않은 비밀번호 입력

올바르지 않은 비밀번호 입력 시 
실제 시도한 입력과 
팝업의 카운트가 일치하지 않는 현상입니다.
- 실제 시도 2회 시, 팝업은 1회 시도로 나타나고 있어 확인 부탁드립니다.

영상: https://youtu.be/vRuCOEXPros

발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Laptop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by Seo-Wonho** [comment]
안녕하세요. 라미와 N2 로 확인한 결과 정상적으로 카운트되고 있는 것을 확인했습니다. 혹시 다시 한 번 확인해주실 수 있으실까요?? 펜의 기종과 버전도 확인 부탁드립니다. 감사합니다!
![11](https://user-images.githubusercontent.com/94896134/153523174-70710bcf-9200-40e7-9f46-6e225892034a.png)
<img width="1440" alt="22" src="https://user-images.githubusercontent.com/94896134/153523186-d559030b-fca0-4ea6-ab9e-1d29684b1701.png">

**Comment by Hansol16** [comment]
@Seo-Wonho  안녕하세요, 연구원님.  사용한 펜은 M1(v3.02.0184), M1+(v1.09.0133) 이며, 
재택근무 중 발생한 이슈로 회사에서 재현 시도하였으나 발생되지 않아 이슈 close합니다.
