### ISSUE TITLE
[내용 지우기] 파일로 보드 생성 시, 필기 내용 없음에도 아이콘 활성화된 현상

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#415]
발견 일시 : 2022.02.10
위치 : 페이지 뷰> 내용 지우기

설명:
파일로 보드 생성(PDF 등) 시
그리다보드에서 필기한 내용 없음에도 
내용 지우기(필기) 아이콘 활성화되어 있는 현상으로 확인 부탁드립니다.

발생 환경 (OS/크롬 버전) : Win 11 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Laptop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by Minkyum-Kim** [comment]
필기 지우기는 항상 활성화 되어 있습니다

**Comment by Hansol16** [comment]
정책상 필기 지우기는 항상 활성화로 close 합니다
