### ISSUE TITLE
[스마트 플레이트] 부기보드와 스마트 플레이트 사용 호환성 검토 건

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#416]
날짜 : 22.02.11
설명 :

이번 업데이트에 부기보드사용 기능이 추가되면서, 기존 출시제품인 Smart Plate 에 필기 시 필기 방향이 가로(Landscape)로 고정되어 필기가 되는 이슈가 확인되었습니다. 

- 상용버전(gridaboard.io) 에서는 그리다보드 페이지 회전 관계없이 portrait 필기 가능 

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 이번에 출시된 부기보드와 기존의 스마트 플레이트는 동일하게 사용될 수 있도록 기획되었습니다. 따라서, 부기보드와 마찬가지로 스마트 플레이트 또한 필기 방향은 가로로 시작될것이고, 회전시에도 현실 스마트 플레이트를 회전해 사용해야 합니다.

**Comment by neoJD** [comment]
질문이 있습니다.
새 보드 생성한 후에 부기보드를 사용할 경우 현실 부기보드는 세로로 놓아서 사용(Default)하도록 되어있있습니다. 

스마트 플레이트는 자체로 가로로 놓고 사용하도록 구성되어있는 제품임에도 불구하고(PUI 위치등을 고려했을때) 

현실 스마트 플레이트를 세로로 놓고 사용해야한다는 말씀이신가요? 

부기보드 같은 경우는 그리다보드의 페이지 회전에 따라 현실 보드를 돌려쓸수 있도록 구현되어있지만,
스마트플레이트는 그렇지 못한 것 같아서 추가 문의 드립니다.

@Osupernov  기획 확인 부탁드립니다.

**Comment by neoJD** [comment]
확인 결과 기존 플레이트 사용자의 경우 녹음 PUI를 기준으로 + 심볼 위치확인하도록 사용 안내 예정

**Comment by Osupernov** [comment]
@neoJD  책임님, 우선 회전 시 돌려서 사용하는 게 맞습니다. PUI 부분이 돌아가지만 사용하기엔 큰 무리가 없어 서비스 사용성 개선을 위해서 변경했습니다. 

기존 플레이트는 가로형으로 제작되어 가로형 문서를 불러와 필기할 땐 문제없었지만, 세로형 문서를 불러와서 하는 경우엔 아예 사용을 할 수 없었던 상황이었습니다. 영역도 기존 플레이트의 아주 적은 영역만 사용할 수 있고, 그마저도 페이지와 매핑이 되지 않아 사용이 불가능한 상태였습니다. 참고 부탁 드립니다..

기존 유저를 위한 추가 안내는 그리다보드 '깃북 매뉴얼'과 3월 안으로 배포 예정인 '그리다보드 유저매뉴얼'에서 안내 예정입니다.
