### ISSUE TITLE
[무한 로딩] 기존에 작성해두었던 보드 수정 -> 저장 시 TypeError: Cannot read properties of undefined (reading 'removedPage') 발생 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#448]
날짜 : 22.02.24
설명 :

기존에 저장된 보드를 수정 후 저장(덮어쓰기) 시 아래와 같은 에러 문구 출력 확인하였습니다. 
해당 에러 메세지가 출력될 경우, 저장되지 않고 무한로딩에 빠지게 됩니다. 
현재까지 2회 이슈 재현되었으며, 추가 테스트 진행해보도록 하겠습니다. 

BoardListPageFunc.tsx:404 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'removedPage')
    at BoardListPageFunc.tsx:404:16
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)

발생 빈도 : sometimes
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 책임님 현재 확인한 바로는 기존에 저장된 보드를 수정할 때 페이지 추가/삭제와 같은 동작을 수행한 후 덮어씌우기 할 시 해당 에러문구가 나타나는것을 확인하였습니다. 수정 후 업데이트 하겠습니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by neoJD** [comment]
수정 확인 후 이슈 종료처리 합니다.
