### ISSUE TITLE
[Hover] PDF 불러오기로 보드 생성 후 호버 이동이 90도 회전된 채로 표현되는 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#449]
날짜 : 22.02.24
설명 :

[재현 경로]

1. PDF로 새 보드 생성

2. 펜 연결

3. (부기보드에 Pen Down 없이) 호버 이동시도 

Pen down 없이 보드에 근접해서 호버만 출력해서 움직여볼 경우 90도 회전된 채로 호버가 움직이는 것을 확인 할 수 있습니다. 

이 현상은 부기보드를 한번 터치 할 경우 정상적으로 동작합니다. 

내용 검토 부탁드립니다. 

발생 빈도 : 항상 
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by neoJD** [comment]
수정 확인 후 이슈 종료처리합니다.
