### ISSUE TITLE
[회전] 회전(Tap) 후 클릭 전까지 회전이 되지 않는 이슈

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#450]
날짜 : 22.02.24
설명 :

회전 동작 후 마우스 클릭(Click) 또는 펜 필기가 들어가기 전까지 회전이 반영되지 않는 이슈입니다. 

발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by MHCHOI3** [comment]
안녕하세요. 책임님 회전을 한 후 web상으로 보여지는 페이지 회전이 바로 적용되지 않으신다는 말씀이신가요?

**Comment by neoJD** [comment]
넵 맞습니다.  회전 후 클릭, 마우스 휠 동작, 펜 필기... 등등의 추가적인 동작이 없기전까지는 화면이 회전되지 않습니다.
![이미지 1](https://user-images.githubusercontent.com/61952421/155448971-5776c11c-3aa5-40c8-b781-fb29d5139bcd.png)

**Comment by Seo-Wonho** [comment]
안녕하세요. 수정 완료하였습니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by neoJD** [comment]
수정 확인 후 종료처리합니다.
