### ISSUE TITLE
[페이지리스트/문의] 새로운 페이지 생성 시, 페이지 리스트에서 해당 페이지 위치로 이동 되지 않는 현상

### ISSUE THREAD

**Issue by Hansol16** [neostudio-team/GridaBoard2#453]
발견 일시 : 2022.02.24
위치 : 페이지 리스트 > 썸네일

설명:
새 페이지 추가 시 페이지리스트에
사용하는 페이지의 썸네일 초점이 잡히는데 
해당 페이지 리스트로 스크롤되어 이동 되지 않아 문의드립니다.

영상: https://youtu.be/FQB1VuKmpts

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H2 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : Desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 김한솔
사용계정 : 구글로그인([hansol@neolab.net](mailto:hansol@neolab.net))

**Comment by Seo-Wonho** [comment]
안녕하세요. 수정 완료했습니다.

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by Hansol16** [comment]
해당 이슈 수정 확인되어 close합니다.
