### ISSUE TITLE
[플레이트모드] 페이지(portrait)를 회전 후 저장 -> 재진입 시 심볼 위치 이슈 발생 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#458]
날짜 : 22.02.24
설명 :

페이지를 회전 후 저장 -> 보드 재진입 -> 심볼 위치 확인해보면 심볼 위치에 문제가 생기는 이슈입니다.

자세한 재현 경로는 아래 첨부된 링크에서 영샹 참조 부탁 드립니다. 

영상 : https://drive.google.com/file/d/1XghN9tF1oFhxcuvnVEeoHraK1dufj5M-/view?usp=sharing

발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by neoJD** [comment]
추가 설명합니다. 영상의 끝자락에 심볼 위치가 바뀌게되는데, 그 상태에서 다시 원래 pdf의 portrait 상황으로 회전을 돌리려고 하다보면 아래 이미지처럼 왼쪽 상단에 + 심볼이 생기게되는 현상이 발생합니다.
![심볼위치](https://user-images.githubusercontent.com/61952421/155465054-779de635-8aab-40f4-b4a5-330ebbfcd07b.png)

**Comment by Minkyum-Kim** [comment]
해당 이슈 테스트 서버에 반영하였습니다.

**Comment by neoJD** [comment]
수정 완료 확인 후 종료처리합니다.
