### ISSUE TITLE
[페이지 추가] .grida 파일 추가 시 기존에 작성한 페이지 모두 사라지는 현상(기획 문의)

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#466]
위치 : 페이지 뷰

설명 :

기존 빈 페이지로 페이지 생성 및 필기 후 "새파일 추가" 로 .grida 파일을 선택할 경우 기존에 작성해두었던 페이지들이 모두 사라지는 이슈입니다. 

다른 포맷의 파일(.pdf)을 추가할 경우 기존 작성한 페이지 아래 추가한 파일의 페이지들이 생성되는데 
동작의 차이가 발생하는 이유가 있을까요?

기획 문의 드립니다. 

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인([neo.jd@neolab.net](mailto:neo.jd@neolab.net))

**Comment by Minkyum-Kim** [comment]
현재 그리다보드에서는 grida 파일끼리의 병합을 허용하지 않고 있습니다. 

기본적으로 그리다보드를 동작시키게 되면, 내부적으로 grida data의 개념이 생성이 되고, 여기에 각종 pdf들을 추가하는 형태이지만, grida 파일을 불러오게 되면, 프로그램이 가지고 있던 grida data와 새로 불러온 grida 파일의 data를 병합 할 수 없어서 가지고 있는 데이터를 버리고, 새로운 data를 불러오는 형태입니다.

**Comment by Minkyum-Kim** [comment]
병합을 하지 않는 이유는, 병합을 하게 될경우 SOBP 내용이 충돌이 날 가능성과, 이에 따른 사이드 이팩트가 정리되지 않을 가능성이 높아서 인것으로 알고 있습니다.

**Comment by neoJD** [comment]
"병합되지 않는 것이 정책"

이슈 종료 처리하도록 하겠습니다.
