### ISSUE TITLE
[그리다보드 첫 시작시에 color toggle 문제]

### ISSUE THREAD

**Issue by hwansang** [neostudio-team/GridaBoard2#5]
[이슈 내용]

첫 시작시 default로 지정되어있는 color의 버튼 toggle이 되어있지 않습니다.

![image](https://user-images.githubusercontent.com/75828099/104165626-fa5b7200-543c-11eb-84b7-e5bd57efcd7d.png)

발생 기기 : web
발생 빈도 : 항상
버전 : 2.0

**Comment by minihallo-neo** [comment]
default인 검정색으로 toggle 되도록 처리
