### ISSUE TITLE
[ncode 인쇄시 인쇄 준비 중 dialog가 특정 percent에서 진행되지 않는 문제]

### ISSUE THREAD

**Issue by hwansang** [neostudio-team/GridaBoard2#53]
[이슈 내용]

ncode로 인쇄 시 인쇄 준비 중 dialog가 특정 percent에서 더 이상 진행되지 않습니다.

발생 기기 : web
발생 빈도 : 항상
버전 : 2.0

**Comment by minihallo-neo** [comment]
해결함
