### ISSUE TITLE
[마우스펜 왼쪽 끝으로 가면 오른쪽 끝까지 스트로크가 그려지는 문제]

### ISSUE THREAD

**Issue by hwansang** [neostudio-team/GridaBoard2#74]
[이슈 내용]

마우스펜으로 왼쪽 끝까지 스트로크를 그리면 오른쪽 끝까지 튀면서 스트로크가 그려집니다.

발생 기기 : web
발생 빈도 : 항상
버전 : 2.0

**Comment by hwansang** [comment]
해결되었습니다

**Comment by minihallo-neo** [comment]
해결함
commit : 87530501e0d1a7393cc4009f6ea1645678a441dd
