### ISSUE TITLE
페이지 색상 및 버튼 테두리 표시

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#78]
- 발견 일시 : 2021.03.19
- 위치 : 버튼 및 페이지 영역
- 화면 : 캡처 포함
- 항목 및 설명 : 페이지 영역이 테두리와 파란색으로 표시되고 있고 버튼도 테두리 표시되고 있어서 이 부분 안보이게 수정부탁드립니다.
- OS : windows10
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111718451-48f21600-889d-11eb-939c-10f9b81d77b0.png)
![image](https://user-images.githubusercontent.com/80931389/111718565-7dfe6880-889d-11eb-83b7-e0c5b78fac51.png)

**Comment by minihallo-neo** [comment]
썸네일에서 선택한 페이지를 빨간색 테두리로 표시하도록 바꿨고 페이지 영역 테두리 제거했습니다.
