### ISSUE TITLE
pdf파일 불러올 때 오류

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#80]
- 발견 일시 : 2021.03.19
- 위치 : 불러오기 > 파일 업로드(.pdf)
- 화면 : 캡처 포함
- 항목 및 설명 : pdf파일 불러오기 시도 시, 아예 불러와지지 않거나 그리다파일 불러오기 시도 시와 동일하게 메뉴 사라지는 이슈 있습니다. 확인 부탁드립니다.
- 사용 OS환경 : windows 10
- 발생 빈도 : 거의 항상
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111719111-8efba980-889e-11eb-888d-db49f5b76f23.png)
![image](https://user-images.githubusercontent.com/80931389/111719118-9458f400-889e-11eb-964f-32b50c441205.png)

**Comment by minihallo-neo** [comment]
같은 pdf는 중복해서 올라가지 않도록 설계되어 있는데 이 경우엔 안내 메세지를 따로 띄우거나 해야할 것 같습니다
