### ISSUE TITLE
저장하기 메뉴 창크기 조정장하기 메뉴 창크기 조정

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#81]
- 발견 일시 : 2021.03.19
- 위치 : 저장하기
- 화면 : 캡처 포함
- 항목 및 설명 : 저장하기 버튼 클릭 시, 메뉴 명 스크롤 표시되고 있는데 가로 길이 좀 더 늘려서 스크롤 표시 안되게 부탁드립니다.
- 사용 OS 환경 : Windows 10
- 발생 빈도 : 항상
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111719445-37aa0900-889f-11eb-8cd5-3369a251bb6c.png)

**Comment by minihallo-neo** [comment]
수정했습니다
