### ISSUE TITLE
마우스, 펜 함께 사용 시 툴바 기능 마우스 적용 안됨

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#82]
- 발견 일시 : 2021.03.19
- 위치 : 마우스 입력
- 화면 : 캡처 포함
- 항목 및 설명 : 마우스와 펜을 함께 사용할 때 펜 툴바(색상, 두께 변경) 기능이 마우스에는 적용이 안됩니다. 기술적으로 불가능한건지 버그인건지 확인부탁드립니다.
- 사용 OS 환경 : windows 10
- 발생 빈도 : 항상
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111719637-9c656380-889f-11eb-9ca0-e6c1b2182e05.png)

**Comment by minihallo-neo** [comment]
함께 사용할 때 마우스와 펜 모두 색상, 두께 등이 같이 적용되도록 수정했습니다.
