### ISSUE TITLE
페이지 화면 회전 시 배경지 회전 지연

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#84]
- 발견 일시 : 2021.03.19
- 위치 : 화면 회전
- 화면 : 캡처 포함
- 항목 및 설명 : 페이지 회전 시, 배경이 회전되는데 시간 지연이 있습니다.
- 사용 OS 환경 : windows 10
- 발생 빈도 : 항상
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111732867-e3605280-88b9-11eb-8703-ef0236e54220.png)

**Comment by minihallo-neo** [comment]
이 부분은 예전에 대표님과 의논했었는데 문제가 되지 않는다고 결론나서 우선 이렇게 두기로 했습니다.
