### ISSUE TITLE
인쇄 옵션 설정 화면에 블루프린트 안내 라벨로 표시

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#86]
- 일시 : 2021.03.19
- 위치 : 프린트 > 인쇄옵션
- 화면 : 디자인 기획안 캡처 포함
- 항목 및 설명 : 인쇄 옵션에 일반 용지 인쇄 시 파랗게 인쇄된다는 안내 문구 필요합니다. 확인부탁드립니다.
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111747194-5ecdfe00-88d2-11eb-8a3d-3f6c89297fa4.png)

**Comment by minihallo-neo** [comment]
안내 문구 추가했습니다

**Comment by KiyeonSeo** [comment]
2021.03.24 서기연 처리 완료 확인
