### ISSUE TITLE
페이지 리스트 영역 잘림

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#87]
- 발견 일시 : 2021.03.19
- 위치 : 좌측 페이지리스트
- 화면 : 캡처 포함
- 항목 및 설명 : 좌측 페이지 리스트 열었을 때 영역 잘려서 보임, 해상도에 상관없이 잘립니다
- 발생기기 : LG gram 노트북
- 발생 빈도 : 항상
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

[화면]
![image](https://user-images.githubusercontent.com/80931389/111750953-3ac0eb80-88d7-11eb-9220-1b34c1fe5528.png)

**Comment by minihallo-neo** [comment]
수정됐습니다
commit : 1db8ef29ceac4cd3a6b7afe23470c1fa96e45ef8
