### ISSUE TITLE
페이퍼 컨트롤러 적용 범위 확인

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#92]
- 일시 : 2021.03.22
- 위치 : 페이퍼 컨트롤러(P2UI)
- 화면 : 없음(그리다보드 컨트롤러 지류 참고)
- 항목 및 설명 : 그리다보드 페이퍼 컨트롤러 적용되어야할 범위 안내드립니다.
  1. 펜 타입(펜, 형광펜, 지우개)
  2. 펜 두께(1~3)
  3. 펜 색상(1~10)
  4. 포인터
  5. 확대/축소
  6. 너비/높이 맞춤
  7. 페이지 이동
 - 앱버전 : https://gridaboard-v2-test.web.app/
 - 등록자 : 김혜원

**Comment by KiyeonSeo** [comment]
위의 항목이 1차라고 한다면... 2차에는 전체삭제(휴지통 P2UI), Hide/Show Menu 제공이 필요한데요. 
우선 1차에서 제공되지 않는 P2UI 값이 들어오면 alert "현재 준비중인 기능입니다."정도의 안내가 필요합니다.
