### ISSUE TITLE
그리다보드 단축키 및 툴팁 적용

### ISSUE THREAD

**Issue by hwkim000** [neostudio-team/GridaBoard2#93]
- 일시 : 2021.03.23
- 위치 : 단축키/툴팁
- 화면 : 없음
- 항목 및 설명 : 아래 링크에 그리다보드 단축키 관련 정리해뒀습니다. 확인하시고 적용부탁드립니다.
-https://docs.google.com/spreadsheets/d/1Xxn6194jG-q8dDS0UsHIe9zLryevAKK2o4Uwonto2zQ/edit#gid=591694450
- 앱버전 : https://gridaboard-v2-test.web.app/
- 등록자 : 김혜원

**Comment by KiyeonSeo** [comment]
@hwansang @sexyflash-neo 
기존 그리다보드 단축키 중 네오스튜디오 단축키와 겹치는 부분은 네오스튜디오 기준으로 정리하였습니다. 
참고하십시오.
