### ISSUE TITLE
[UI] Drop Down Box 이미지에 백그라운드 아이콘 잔상이 남는 이슈(그림첨부)

### ISSUE THREAD

**Issue by KiyeonSeo** [neostudio-team/GridaBoard2#97]
https://github.com/neostudio-team/GridaBoard/issues/32

- 안예지 파트장님 등록
-버전: 그리다 보드 2.0
-접속경로 : https://gridaboard-v2-test.web.app/

Drop Down Box 이미지에 백그라운드 아이콘 잔상이 남는 이슈 입니다.
"프린트" 메뉴의 경우 Text Box 길이 보다 더 길게 포인터가 선택됩니다.
![제목 없음](https://user-images.githubusercontent.com/57121184/112241818-132ea200-8c8e-11eb-88ca-2b4f060c15a1.png)

**Comment by KiyeonSeo** [comment]
@yeji-qa 책임님, 처리 되었습니다. 확인 요청 드립니다.

**Comment by yeji-qa** [comment]
@KiyeonSeo 수석님, 해당 이슈 재현됩니다.  
저장하기, 불러오기, 화면비율(100%) 메뉴 첫 진입 시 Drop Down Box에 잔상이 생기고 하위 메뉴 선택 시 잔상이 사라집니다. 

*동영상: https://www.youtube.com/watch?v=UxdmZRGoAPY
